(()=>{
const C=window.TELECOD_CONFIG||{};
const url=String(C.SUPABASE_URL||window.TELECOD_SUPABASE_URL||'').trim();
const key=String(C.SUPABASE_ANON_KEY||window.TELECOD_SUPABASE_ANON_KEY||'').trim();
const configured=window.supabase&&url&&key&&!/YOUR[_-]|PROJECT\b|PUBLISHABLE|ANON[_-]?KEY/i.test(url+' '+key);
const sup=configured?window.supabase.createClient(url,key):null;
const $=s=>document.querySelector(s);
let loginIdentifierValue='';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg,type=''){const el=$('#authToast');if(!el)return;el.textContent=msg;el.className='toast show '+type;clearTimeout(window.__authToast);window.__authToast=setTimeout(()=>el.className='toast',4500)}
function validGmail(v){return /^[^@\s]+@gmail\.com$/i.test(v.trim())}
function showPanel(mode){['loginPanel','registerPanel','forgotPanel','registerSuccessPanel'].forEach(id=>{const e=$('#'+id);if(e)e.hidden=true});const id=mode==='register'?'registerPanel':mode==='forgot'?'forgotPanel':mode==='registerSuccess'?'registerSuccessPanel':'loginPanel';const target=$('#'+id);if(target)target.hidden=false;if(mode==='login'){if($('#loginPasswordForm'))$('#loginPasswordForm').hidden=true;if($('#identifierMessage'))$('#identifierMessage').hidden=true;if($('#identifierStatus'))$('#identifierStatus').textContent='';$('#loginIdentifier')?.focus()}}
async function lookup(identifier){if(!sup)return{error:'Supabase belum dikonfigurasi.'};const value=identifier.trim();if(!value)return{error:'Masukkan Gmail atau username.'};if(validGmail(value)){const {data,error}=await sup.rpc('lookup_user_by_email',{p_email:value.toLowerCase()});if(error)return{error:error.message};const user=Array.isArray(data)?data[0]:data;if(user?.is_banned)return{error:'Akun kamu diblokir admin.'};if(user?.id)return{user,identifier:value,email:value};return{notFound:true}}
const {data,error}=await sup.rpc('resolve_username_login',{p_username:value});if(error)return{error:error.message};const row=Array.isArray(data)?data[0]:data;const email=typeof row==='string'?row:row?.auth_email;if(!email)return{notFound:true};if(row?.is_banned)return{error:'Akun kamu diblokir admin.'};return{user:{username:row?.username||value,display_name:row?.display_name||row?.username||value,id:row?.id||null},identifier:value,email};}
function init(){
 document.querySelectorAll('.toggle-password').forEach(btn=>btn.addEventListener('click',()=>{const input=$('#'+btn.dataset.target);if(!input)return;const visible=input.type==='password';input.type=visible?'text':'password';const icon=btn.querySelector('i');if(icon)icon.className=visible?'fa-solid fa-eye-slash':'fa-solid fa-eye'}));
 $('#showLogin')?.addEventListener('click',()=>location.href='/auth/login.html');$('#showRegister')?.addEventListener('click',()=>location.href='/auth/register.html');$('#registerSuccessLogin')?.addEventListener('click',()=>location.href='/auth/login.html');$('#backToLogin')?.addEventListener('click',()=>location.href='/auth/login.html');$('#forgotFromRegister')?.addEventListener('click',()=>location.href='/auth/forgot.html');
 $('#loginIdentifier')?.addEventListener('input',()=>{if($('#loginPasswordForm'))$('#loginPasswordForm').hidden=true;if($('#identifierStatus'))$('#identifierStatus').textContent='';if($('#identifierMessage'))$('#identifierMessage').hidden=true});
 $('#loginIdentifierForm')?.addEventListener('submit',async e=>{e.preventDefault();const input=$('#loginIdentifier'),status=$('#identifierStatus'),msg=$('#identifierMessage');const value=input.value.trim();status.textContent='⏳';msg.hidden=true;const r=await lookup(value);if(r.error){status.textContent='✕';msg.hidden=false;msg.className='auth-message error';msg.textContent=r.error;return}if(r.notFound){status.textContent='✕';msg.hidden=false;msg.className='auth-message error';msg.innerHTML='Akun tidak ada atau belum terdaftar. <button type="button" id="quickRegister">Daftar / Register</button>';$('#quickRegister').onclick=()=>location.href='/auth/register.html';return}status.textContent='✓';msg.hidden=false;msg.className='auth-message success';msg.textContent=`Akun ditemukan. Masuk sebagai ${r.user.display_name||r.user.username||value}.`;loginIdentifierValue=value;window.__telecodLoginEmail=r.email||'';$('#loginWelcome').innerHTML=`✓ Masuk sebagai <strong>${esc(r.user.display_name||r.user.username||value)}</strong>`;$('#loginPasswordForm').hidden=false;$('#loginPassword').focus()});
 $('#loginPasswordForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sup)return toast('Supabase belum dikonfigurasi.','error');const password=$('#loginPassword').value;const email=window.__telecodLoginEmail||(validGmail(loginIdentifierValue)?loginIdentifierValue.toLowerCase():'');if(!validGmail(email))return toast('Email akun tidak dapat ditemukan.','error');const {error}=await sup.auth.signInWithPassword({email,password});if(error)return toast('Kata sandi salah. Silakan cek kembali.','error');location.href='/dashboard/'});
 $('#forgotForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sup)return toast('Supabase belum dikonfigurasi.','error');const email=$('#forgotEmail').value.trim().toLowerCase();if(!validGmail(email))return toast('Masukkan Gmail yang valid.','error');const btn=e.currentTarget.querySelector('button[type=submit]');const old=btn.innerHTML;btn.disabled=true;try{const {error}=await sup.auth.resetPasswordForEmail(email,{redirectTo:location.origin+'/reset.html'});if(error)throw error;toast('Link reset berhasil dikirim ke Gmail.','success');setTimeout(()=>location.href='/auth/login.html',700)}catch(err){toast(err?.message||'Gagal mengirim link reset.','error')}finally{btn.disabled=false;btn.innerHTML=old}});
 $('#registerForm')?.addEventListener('submit',async e=>{e.preventDefault();if(!sup)return toast('Supabase belum dikonfigurasi.','error');const username=$('#registerUsername').value.trim().toLowerCase(),email=$('#registerEmail').value.trim().toLowerCase(),password=$('#registerPassword').value,confirm=$('#registerConfirm').value;if(!/^[a-z0-9_]{3,32}$/.test(username))return toast('Username 3-32 karakter: huruf, angka, underscore.','error');if(!validGmail(email))return toast('Gunakan alamat Gmail yang valid.','error');if(password.length<6)return toast('Kata sandi minimal 6 karakter.','error');if(password!==confirm)return toast('Konfirmasi kata sandi tidak sama.','error');const registerUrl=String(C.REGISTER_FUNCTION_URL||'').trim();if(!registerUrl)return toast('Fungsi registrasi belum dikonfigurasi.','error');const btn=e.currentTarget.querySelector('button[type=submit]'),old=btn.innerHTML;btn.disabled=true;try{const r=await fetch(registerUrl,{method:'POST',headers:{'Content-Type':'application/json',apikey:C.SUPABASE_ANON_KEY,Authorization:`Bearer ${C.SUPABASE_ANON_KEY}`},body:JSON.stringify({username,email,password})});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||out.message||'Registrasi gagal.');e.currentTarget.reset();showPanel('registerSuccess');toast('Registrasi berhasil. Akun kamu sudah aktif.','success')}catch(err){toast(err?.message||'Registrasi gagal.','error')}finally{btn.disabled=false;btn.innerHTML=old}});
 const google=async()=>{if(!sup)return toast('Supabase belum dikonfigurasi.','error');const {error}=await sup.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+'/dashboard/'} });if(error)toast(error.message||'Login Google gagal.','error')};$('#googleLoginBtn')?.addEventListener('click',google);$('#googleRegisterBtn')?.addEventListener('click',google);
 const mode=document.body.dataset.authPage||'login';showPanel(mode);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();