document.addEventListener("DOMContentLoaded",()=>{
"use strict";
const $=id=>document.getElementById(id), sb=()=>window.sb;
const toast=(m,t="info")=>window.TC?.toast?window.TC.toast(m,t):alert(m);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m]));
const access=()=>document.querySelector('input[name="access"]:checked')?.value||"free";
function setLoading(on){const b=$("submitBtn");if(!b)return;b.disabled=on;b.setAttribute("aria-busy",String(on));const n=b.querySelector(".normal"),l=b.querySelector(".loading");if(n)n.hidden=on;if(l)l.hidden=!on}
function requireClient(){if(!sb())throw new Error("Supabase belum siap. Refresh halaman dan coba lagi.")}
const slugify=s=>String(s||"").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,70);let bots=[];
function sync(){const paid=access()==="paid";$("priceBox").hidden=!paid;$("price").disabled=!paid;if(!paid)$("price").value="0"}
function validate(){const title=$("title").value.trim(),bot=$("botId").value,content=$("content").value.trim(),desc=$("description").value.trim(),a=access(),price=a==="paid"?Number($("price").value||0):0;if(title.length<2||title.length>120)return toast("Judul harus 2–120 karakter.","error"),null;if(!bot)return toast("Pilih bot yang sudah ditambahkan admin.","error"),null;if(!content)return toast("Code / Delivery wajib diisi.","error"),null;if(a==="paid"&&(!Number.isInteger(price)||price<5000||price>150000||price%1000))return toast("Harga Paid harus Rp5.000–Rp150.000 dan kelipatan Rp1.000.","error"),null;return{title,bot,content,desc,a,price}}
async function loadBots(){const select=$("botId");if(!select)return;select.disabled=true;select.innerHTML='<option value="">Memuat bot...</option>';try{requireClient();const {data,error}=await sb().rpc("get_active_approved_bots");if(error)throw error;bots=Array.isArray(data)?data:[];if(!bots.length){select.innerHTML='<option value="">Belum ada bot aktif dari admin</option>';$("botStatus").hidden=false;return}select.disabled=false;$("botStatus").hidden=true;select.innerHTML='<option value="">Pilih bot...</option>'+bots.map(b=>`<option value="${esc(b.id)}">🤖 @${esc(String(b.bot_username||"").replace(/^@/,""))}${b.bot_name&&b.bot_name!==b.bot_username?' — '+esc(b.bot_name):""}</option>`).join("")}catch(e){console.error(e);select.innerHTML='<option value="">Bot gagal dimuat</option>';$("botStatus").hidden=false;$("botStatus").textContent="Daftar bot belum dapat dimuat. Jalankan SQL final dan pastikan ada bot aktif."}}
function finish(v,slug){const url=`${location.origin}/c/${v.a==="paid"?"p":"f"}/${encodeURIComponent(slug)}`,r=$("result");r.hidden=false;r.innerHTML=`<div class="result-icon"><i class="fa-solid fa-circle-check"></i></div><h2>Code berhasil dipublikasikan</h2><p><b>${esc(v.title)}</b> menggunakan bot <b>@${esc(v.botUsername)}</b>.</p><div class="result-url"><input readonly value="${esc(url)}"><button id="copyUrl" type="button"><i class="fa-regular fa-copy"></i></button></div><div class="result-actions"><a class="btn primary" href="${esc(url)}">Buka Code</a><a class="btn secondary" href="my-products.html">Code Saya</a></div>`;$("copyUrl").onclick=async()=>{try{await navigator.clipboard.writeText(url);toast("Link berhasil disalin.","success")}catch{toast("Gagal menyalin link.","error")}};r.scrollIntoView({behavior:"smooth",block:"center"})}
document.querySelectorAll('input[name="access"]').forEach(x=>x.addEventListener("change",sync));$("description")?.addEventListener("input",()=>$("counter").textContent=$("description").value.length);$("botId")?.addEventListener("change",()=>{const b=bots.find(x=>String(x.id)===$("botId").value);$("botUsernamePreview").textContent=b?"@"+String(b.bot_username||"").replace(/^@/,""):""});
$("createForm")?.addEventListener("submit",async e=>{e.preventDefault();if($("submitBtn").disabled)return;const v=validate();if(!v)return;setLoading(true);try{requireClient();if(v.a==="paid"&&!(await window.TC?.user?.())){location.href="login.html?redirect="+encodeURIComponent(location.href);return}const b=bots.find(x=>String(x.id)===v.bot);if(!b)throw new Error("Bot tidak ditemukan atau sudah dinonaktifkan admin.");const slug=`${slugify(v.title)||"code"}-${crypto.randomUUID().slice(0,8)}`;const {data,error}=await sb().rpc("create_code_content",{p_title:v.title,p_content:v.content,p_slug:slug,p_access_type:v.a,p_price:v.price,p_description:v.desc,p_approved_bot_id:v.bot});if(error)throw error;if(!data?.ok)throw new Error("Database tidak mengonfirmasi pembuatan Code.");finish({...v,botUsername:String(b.bot_username||"").replace(/^@/,"")},data.slug||slug);$("createForm").reset();sync();$("counter").textContent="0";$("botUsernamePreview").textContent="";toast("Code berhasil dipublikasikan.","success")}catch(e){console.error(e);toast(e?.code==="23505"?"Slug sudah digunakan. Silakan coba lagi.":e?.message||"Gagal menyimpan Code.","error")}finally{setLoading(false)}});sync();loadBots();
});