const $=id=>document.getElementById(id); const sb=()=>window.sb;
const toast=(m,t='info')=>window.TC?.toast?window.TC.toast(m,t):alert(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const slugify=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);
const uniqueSlug=title=>{const base=slugify(title)||'content'; const r=crypto?.getRandomValues?crypto.getRandomValues(new Uint8Array(4)):Array.from({length:4},()=>Math.random()*256); return base+'-'+Array.from(r,b=>(Number(b)%36).toString(36)).join('');};
const user=async()=>{const u=await window.TC?.user?.(); if(!u?.id){location.href='login.html?redirect='+encodeURIComponent(location.href);return null;} return u;};
const accessValue=()=>document.querySelector('input[name="access"]:checked')?.value||'free';
const amount=()=>accessValue()==='paid'?Number($('price').value||0):0;
function wireCommon(){document.querySelectorAll('input[name="access"]').forEach(x=>x.addEventListener('change',()=>{$('priceBox').hidden=accessValue()!=='paid'; if(accessValue()!=='paid')$('price').value='0';})); $('description')?.addEventListener('input',()=>{$('counter').textContent=$('description').value.length});}
function validateCommon(){const title=$('title').value.trim(), access=accessValue(), price=amount(); if(title.length<2)return toast('Judul minimal 2 karakter.','error'),null; if(access==='paid' && (!Number.isInteger(price)||price<5000||price>150000||price%1000))return toast('Harga Paid harus Rp5.000–Rp150.000 dan kelipatan Rp1.000.','error'),null; return {title,access,price,description:$('description').value.trim(),slug:uniqueSlug(title)};}
function finish(p,url){const r=$('result');r.hidden=false;r.innerHTML=`<div class="result-icon"><i class="fa-solid fa-check"></i></div><h2>Berhasil dipublikasikan</h2><p><b>${esc(p.title)}</b> sudah tersimpan.</p><div class="result-url"><input readonly value="${esc(url)}"><button type="button" id="copyUrl"><i class="fa-regular fa-copy"></i></button></div><div class="result-actions"><a class="btn primary" href="${esc(url)}">Buka Konten</a><a class="btn secondary" href="my-products.html">Konten Saya</a></div></div>`; $('copyUrl').onclick=async()=>{try{await navigator.clipboard.writeText(url);toast('Link berhasil disalin.','success')}catch{toast('Tidak bisa menyalin link.','error')}}; r.scrollIntoView({behavior:'smooth',block:'center'});}
function submitState(on){$('submitBtn').disabled=on;$('submitBtn .normal').hidden=on;$('submitBtn .loading').hidden=!on;}
document.addEventListener('DOMContentLoaded',()=>{wireCommon();$('createForm').addEventListener('submit',async e=>{e.preventDefault();if($('submitBtn').disabled)return;const c=validateCommon();if(!c)return;const content=$('content').value.trim();if(!content)return toast('Code / Delivery wajib diisi.','error');const u=await user();if(!u)return;submitState(true);try{const {error}=await sb().from('telegram_products').insert({owner_id:u.id,title:c.title,slug:c.slug,type:'code',product_type:'code',access_type:c.access,bot_username:null,telegram_bot_id:null,price:c.price,description:c.description,content,thumbnail_url:$('thumbnail').value.trim()||null,category:'General',status:'published'});if(error)throw error;finish(c,location.origin+'/c/'+(c.access==='paid'?'p':'f')+'/'+encodeURIComponent(c.slug));$('createForm').reset();$('priceBox').hidden=true;$('counter').textContent='0';}catch(e){console.error(e);toast(e?.code==='23505'?'Slug bentrok, silakan klik Publikasikan lagi.':e?.message||'Gagal menyimpan Code.','error')}finally{submitState(false)}})});