/* PasTele — CREATE CODE BOT — SQL SYNC */
document.addEventListener('DOMContentLoaded',()=>{
'use strict';
const $=id=>document.getElementById(id), sb=()=>window.sb;
const toast=(m,t='info')=>window.TC?.toast?window.TC.toast(m,t):alert(m);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const slugify=s=>String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,70);
const uniqueSlug=title=>`${slugify(title)||'code'}-${crypto?.randomUUID?crypto.randomUUID().slice(0,8):Math.random().toString(36).slice(2,10)}`;
const access=()=>document.querySelector('input[name="access"]:checked')?.value||'free';
const user=async()=>{const u=await window.TC?.user?.();if(!u?.id){location.href='login.html?redirect='+encodeURIComponent(location.href);return null}return u};
let bots=[];
function setLoading(on){const b=$('submitBtn');if(!b)return;b.disabled=on;b.querySelector('.normal')?.toggleAttribute('hidden',on);b.querySelector('.loading')?.toggleAttribute('hidden',!on)}
function wire(){document.querySelectorAll('input[name="access"]').forEach(r=>r.addEventListener('change',()=>{$('priceBox').hidden=access()!=='paid';if(access()!=='paid')$('price').value='0'}));$('description')?.addEventListener('input',()=>{$('counter').textContent=$('description').value.length});$('botId')?.addEventListener('change',()=>{const b=bots.find(x=>String(x.id)===$('botId').value);if(b){$('botUsernamePreview').textContent='@'+String(b.bot_username||'').replace(/^@/,'')}})}
async function loadBots(){const select=$('botId');if(!select)return;select.innerHTML='<option value="">Memuat bot...</option>';try{const {data,error}=await sb().from('approved_bots').select('id,bot_username,bot_name,bot_id').eq('is_active',true).order('bot_name',{ascending:true});if(error)throw error;bots=data||[];if(!bots.length){select.innerHTML='<option value="">Belum ada bot aktif dari admin</option>';select.disabled=true;$('botStatus').hidden=false;return}select.disabled=false;$('botStatus').hidden=true;select.innerHTML='<option value="">Pilih bot...</option>'+bots.map(b=>`<option value="${esc(b.id)}">🤖 @${esc(String(b.bot_username||'').replace(/^@/,''))}${b.bot_name&&b.bot_name!==b.bot_username?' — '+esc(b.bot_name):''}</option>`).join('')}catch(e){console.error(e);select.innerHTML='<option value="">Bot gagal dimuat</option>';select.disabled=true;$('botStatus').hidden=false;$('botStatus').textContent='Daftar bot belum dapat dimuat. Pastikan SQL final sudah dijalankan.'}}
function validate(){const title=$('title').value.trim(), bot=$('botId').value, content=$('content').value.trim(), desc=$('description').value.trim(), a=access(), price=a==='paid'?Number($('price').value||0):0;if(title.length<2||title.length>120){toast('Judul harus 2–120 karakter.','error');return null}if(!bot){toast('Pilih bot yang sudah ditambahkan admin.','error');return null}if(!content){toast('Code / Delivery wajib diisi.','error');return null}if(a==='paid'&&(!Number.isInteger(price)||price<5000||price>150000||price%1000)){toast('Harga Paid harus Rp5.000–Rp150.000 dan kelipatan Rp1.000.','error');return null}if(desc.length>3000){toast('Deskripsi maksimal 3.000 karakter.','error');return null}return {title,bot,content,desc,a,price}}
function finish(data,url){const r=$('result');r.hidden=false;r.innerHTML=`<div class="result-icon"><i class="fa-solid fa-circle-check"></i></div><h2>Code berhasil dipublikasikan</h2><p><b>${esc(data.title)}</b> menggunakan bot <b>@${esc(data.botUsername)}</b>.</p><div class="result-url"><input readonly value="${esc(url)}"><button id="copyUrl" type="button" aria-label="Salin link"><i class="fa-regular fa-copy"></i></button></div><div class="result-actions"><a class="btn primary" href="${esc(url)}"><i class="fa-solid fa-arrow-up-right-from-square"></i> Buka Code</a><a class="btn secondary" href="my-products.html"><i class="fa-solid fa-box"></i> Code Saya</a></div>`;$('copyUrl').onclick=async()=>{try{await navigator.clipboard.writeText(url);toast('Link berhasil disalin.','success')}catch{toast('Gagal menyalin link.','error')}};r.scrollIntoView({behavior:'smooth',block:'center'})}
$('createForm')?.addEventListener('submit',async e=>{e.preventDefault();if($('submitBtn').disabled)return;const v=validate();if(!v)return;const u=await user();if(!u)return;const b=bots.find(x=>String(x.id)===v.bot);if(!b)return toast('Bot tidak ditemukan atau sudah dinonaktifkan admin.','error');setLoading(true);try{const slug=uniqueSlug(v.title);const payload={owner_id:u.id,title:v.title,slug,type:'code',product_type:'code',access_type:v.a,bot_id:v.bot,bot_username:String(b.bot_username||'').replace(/^@/,''),telegram_bot_id:b.bot_id??null,price:v.price,description:v.desc,content:v.content,thumbnail_url:null,category:'General',status:'published'};const {error}=await sb().from('telegram_products').insert(payload);if(error)throw error;const route=`${location.origin}/c/${v.a==='paid'?'p':'f'}/${encodeURIComponent(slug)}`;finish({title:v.title,botUsername:String(b.bot_username||'').replace(/^@/,'')},route);$('createForm').reset();$('priceBox').hidden=true;$('counter').textContent='0';$('botUsernamePreview').textContent='';}catch(e){console.error(e);toast(e?.code==='23505'?'Slug atau data bot bentrok. Silakan coba lagi.':e?.message||'Gagal menyimpan Code.','error')}finally{setLoading(false)}});
wire();loadBots();
});
