document.addEventListener('DOMContentLoaded',async()=>{
 let filter='all',items=[];const q=document.getElementById('q');
 const icon=t=>t==='code'?'fa-code':t==='channel'?'fa-broadcast-tower':t==='group'?'fa-users':'fa-link';
 document.querySelectorAll('#tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.v;render()});
 q.oninput=render;
 async function load(){const r=await sb.from('marketplace_public').select('*').order('created_at',{ascending:false}).limit(500);if(r.error)return TC.toast(r.error.message,'error');items=r.data||[];render()}
 function ok(x){const t=String(x.type||'').toLowerCase(),a=String(x.access_type||'').toLowerCase();return (filter==='all'||filter===t||(filter==='link'&&t==='link')||(filter==='free'&&a==='free')||(filter==='paid'&&a==='paid'))&&(`${x.title||''} ${x.creator_name||''} ${x.category||''}`.toLowerCase().includes(q.value.toLowerCase()))}
 function card(x){const id=encodeURIComponent(x.id),t=encodeURIComponent(x.type);return `<a class="card product-card" href="product.html?id=${id}&type=${t}"><div class="thumb"><i class="fa-solid ${icon(x.type)}"></i></div><div class="product-body"><span class="rank">${TC.esc(String(x.access_type||'free').toUpperCase())}</span><h3>${TC.esc(x.title||'Untitled')}</h3><p class="muted">${TC.esc(x.creator_name||'Creator')}</p><div class="row" style="justify-content:space-between"><span><i class="fa-solid fa-eye"></i> ${Number(x.views||0).toLocaleString('id-ID')}</span><b>${Number(x.price||0)?TC.money(x.price):'FREE'}</b></div></div></a>`}
 function list(id,arr){const el=document.getElementById(id);if(!el)return;el.innerHTML=arr.slice(0,10).map((x,i)=>`<a class="list-item" href="product.html?id=${encodeURIComponent(x.id)}&type=${encodeURIComponent(x.type)}"><span><b>#${i+1}</b> ${TC.esc(x.title||'Untitled')}<small class="muted"> · ${Number(x.views||0)} views</small></span><b>${x.price?TC.money(x.price):'FREE'}</b></a>`).join('')||'<div class="empty">Belum ada data.</div>'}
 function render(){document.getElementById('market').innerHTML=items.filter(ok).map(card).join('')||'<div class="empty" style="grid-column:1/-1">Belum ada konten yang dipublikasikan.</div>';list('topLink',items.filter(x=>x.type==='link').sort((a,b)=>b.views-a.views));list('topCode',items.filter(x=>x.type==='code').sort((a,b)=>b.created_at.localeCompare(a.created_at)));list('topChannel',items.filter(x=>x.type==='channel').sort((a,b)=>b.created_at.localeCompare(a.created_at)));list('topGroup',items.filter(x=>x.type==='group').sort((a,b)=>b.created_at.localeCompare(a.created_at)))}
 load();
});