/* PasTele — universal navbar. Intentionally self-contained and scoped. */
document.addEventListener('DOMContentLoaded', async () => {
  const host=document.getElementById('navbar');
  if(!host || host.dataset.ready==='1') return;
  host.dataset.ready='1';
  const isAdmin=location.pathname.includes('/admin/'), base=isAdmin?'../':'';
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const file=(location.pathname.split('/').pop()||'dashboard.html').toLowerCase();
  const same=h=>String(h).split('?')[0].toLowerCase()===file;
  let user=null,profile=null;
  try{if(window.TC?.user) user=await window.TC.user();}catch{}
  try{if(!user&&window.sb?.auth) user=(await window.sb.auth.getUser()).data?.user||null;}catch{}
  try{if(user&&window.sb){const r=await window.sb.from('profiles').select('username,display_name,avatar_url,is_admin,is_premium,subscription_until').eq('id',user.id).maybeSingle();profile=r.data||null;}}catch{}
  const name=profile?.username||profile?.display_name||user?.user_metadata?.username||user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Account';
  const premium=!!(profile?.is_premium&&(!profile?.subscription_until||new Date(profile.subscription_until)>new Date()));
  const groups=isAdmin?[["Admin",[["index.html","fa-chart-pie","Overview"],["users.html","fa-users","Users"],["products.html","fa-box","Products"],["content.html","fa-layer-group","Content"],["orders.html","fa-receipt","Orders"],["payments.html","fa-credit-card","Payments"],["withdrawals.html","fa-money-bill-transfer","Withdrawals"],["notifications.html","fa-bell","Notifications"],["transactions.html","fa-arrow-right-arrow-left","Transactions"],["pastes.html","fa-file-lines","Pastes"],["bots.html","fa-robot","Bots"],["logs.html","fa-list","Logs"]]]]:[["Menu",[["dashboard.html","fa-house","Dashboard"],["marketplace.html","fa-store","Marketplace"]]],["Create",[["create-pastelink.html","fa-link","PasteLink"],["create-code.html","fa-code","Code"],["create-telegram.html?type=channel","fa-users","Group / Channel"]]],["Manage",[["my-products.html","fa-box-open","My Product"],["purchases.html","fa-bag-shopping","Purchases"]]],["Finance",[["wallet.html","fa-wallet","Wallet"],["withdrawals.html","fa-money-bill-transfer","Withdraw"],["transactions.html","fa-arrow-right-arrow-left","Transaction"]]],["Account",[["subscription.html","fa-crown","Langganan"],["premium.html","fa-gem","Premium"],["notifications.html","fa-bell","Notifikasi"],["profile.html","fa-user","Profile"],["settings.html","fa-gear","Setting"],["about.html","fa-circle-info","About"]]]];
  const links=items=>items.map(([h,i,l])=>`<a class="pt-link${same(h)?' active':''}" href="${base}${esc(h)}" ${same(h)?'aria-current="page"':''}><span class="pt-link-icon"><i class="fa-solid ${esc(i)}"></i></span><span class="pt-link-label">${esc(l)}</span><i class="fa-solid fa-chevron-right pt-link-arrow"></i></a>`).join('');
  host.innerHTML=`<header class="pt-nav"><div class="pt-nav-inner"><button class="pt-menu-btn" id="ptMenu" type="button" aria-label="Buka menu"><i class="fa-solid fa-bars"></i></button><a class="pt-brand" href="${base}${isAdmin?'index.html':'dashboard.html'}"><span class="pt-brand-mark"><i class="fa-brands fa-telegram"></i></span><span class="pt-brand-name">PasTele</span></a><span class="pt-spacer"></span><div class="pt-user-wrap"><button class="pt-user-btn" id="ptUser" type="button" aria-expanded="false"><span class="pt-avatar">${profile?.avatar_url?`<img src="${esc(profile.avatar_url)}" alt="">`:'<i class="fa-solid fa-user"></i>'}</span><span class="pt-name">${esc(name)}</span>${premium?'<i class="fa-solid fa-circle-check pt-check"></i>':''}<i class="fa-solid fa-chevron-down pt-chevron"></i></button><div class="pt-dropdown" id="ptDrop" hidden><div class="pt-profile"><span class="pt-avatar pt-avatar-lg">${profile?.avatar_url?`<img src="${esc(profile.avatar_url)}" alt="">`:'<i class="fa-solid fa-user"></i>'}</span><div class="pt-profile-text"><strong>${esc(name)}</strong><small>${isAdmin?'Administrator':premium?'Premium aktif':'Akun aktif'}</small></div></div><div class="pt-account-grid"><div class="pt-account-item"><i class="fa-solid fa-wallet"></i><span>Saldo</span><strong id="ptBalance">Rp 0</strong></div><a class="pt-account-item" href="${base}notifications.html"><i class="fa-solid fa-bell"></i><span>Notifikasi</span><strong id="ptNotif">0</strong></a><button class="pt-account-item" id="ptTheme" type="button"><i class="fa-solid fa-circle-half-stroke"></i><span>Tema</span><strong id="ptThemeText">System</strong></button></div><a class="pt-profile-link" href="${base}${isAdmin?'index.html':'profile.html'}"><i class="fa-solid fa-user-gear"></i> Kelola profil <i class="fa-solid fa-arrow-right"></i></a></div></div></div></header><div class="pt-backdrop" id="ptBackdrop"></div><aside class="pt-drawer" id="ptDrawer" aria-hidden="true"><div class="pt-drawer-head"><div class="pt-drawer-title"><span>${isAdmin?'ADMIN PANEL':'WORKSPACE'}</span><strong>${isAdmin?'Administration':'PasTele Menu'}</strong></div><button class="pt-close-btn" id="ptClose" type="button" aria-label="Tutup menu"><i class="fa-solid fa-xmark"></i></button></div><nav class="pt-menu-scroll">${groups.map(([t,it])=>`<section class="pt-group"><h3>${esc(t)}</h3>${links(it)}</section>`).join('')}</nav><div class="pt-drawer-bottom">${!isAdmin?`<a class="pt-link" href="${base}wallet.html"><span class="pt-link-icon"><i class="fa-solid fa-wallet"></i></span><span class="pt-link-label">Wallet & Saldo</span><i class="fa-solid fa-chevron-right pt-link-arrow"></i></a>`:''}<button class="pt-link logout" id="ptLogout" type="button"><span class="pt-link-icon"><i class="fa-solid fa-right-from-bracket"></i></span><span class="pt-link-label">Log out</span><i class="fa-solid fa-arrow-right pt-link-arrow"></i></button></div></aside>`;
  const menu=document.getElementById('ptMenu'),drawer=document.getElementById('ptDrawer'),back=document.getElementById('ptBackdrop'),userBtn=document.getElementById('ptUser'),drop=document.getElementById('ptDrop');
  const close=()=>{drawer.classList.remove('open');back.classList.remove('open');drawer.setAttribute('aria-hidden','true');document.body.classList.remove('pt-nav-lock');menu.setAttribute('aria-expanded','false')};
  menu.onclick=()=>{drawer.classList.add('open');back.classList.add('open');drawer.setAttribute('aria-hidden','false');document.body.classList.add('pt-nav-lock');menu.setAttribute('aria-expanded','true')};
  document.getElementById('ptClose').onclick=close;back.onclick=close;drawer.querySelectorAll('a').forEach(a=>a.onclick=close);
  userBtn.onclick=e=>{e.stopPropagation();const open=!drop.hidden;drop.hidden=open;userBtn.setAttribute('aria-expanded',String(!open));if(!open)close()};
  document.addEventListener('click',e=>{if(!e.target.closest('.pt-user-wrap')){drop.hidden=true;userBtn.setAttribute('aria-expanded','false')}});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'){close();drop.hidden=true;userBtn.setAttribute('aria-expanded','false')}});
  const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v)||0);
  try{if(user&&window.sb){const r=await window.sb.from('wallets').select('balance,available_balance').eq('user_id',user.id).maybeSingle();document.getElementById('ptBalance').textContent=money(r.data?.available_balance??r.data?.balance??0)}}catch{}
  try{if(user&&window.sb){const r=await window.sb.from('notifications').select('id',{count:'exact',head:true}).eq('user_id',user.id).eq('is_read',false);document.getElementById('ptNotif').textContent=String(r.count||0)}}catch{}
  const themeText=()=>{const m=localStorage.getItem('pastele-theme')||'system';document.getElementById('ptThemeText').textContent=m==='dark'?'Gelap':m==='light'?'Terang':'System'};themeText();document.getElementById('ptTheme').onclick=()=>{if(window.PasTeleTheme?.cycle)window.PasTeleTheme.cycle();else{const a=['system','light','dark'],m=localStorage.getItem('pastele-theme')||'system';localStorage.setItem('pastele-theme',a[(a.indexOf(m)+1)%3]);location.reload()}themeText()};
  document.getElementById('ptLogout').onclick=async e=>{const b=e.currentTarget;b.disabled=true;b.querySelector('.pt-link-label').textContent='Keluar...';try{if(window.TC?.logout)await window.TC.logout();else if(window.Auth?.logout)await window.Auth.logout();else if(window.sb?.auth)await window.sb.auth.signOut();location.href=base+'login.html'}catch{b.disabled=false;b.querySelector('.pt-link-label').textContent='Log out'}};
});
