document.addEventListener("DOMContentLoaded", async () => {
  "use strict";
  const $ = id => document.getElementById(id);
  const qs = new URLSearchParams(location.search);
  const orderId = qs.get("order_id");
  const money = v => window.TC?.money ? window.TC.money(Number(v||0)) : new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
  const esc = v => window.TC?.esc ? window.TC.esc(v) : String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c]));
  const loading=$("paymentLoading"),content=$("paymentContent"),errorBox=$("paymentError"),qr=$("qrWrap"),urlBtn=$("cashUrl"),check=$("checkPayment");
  let timer=null, creating=false;
  const fail=msg=>{if(loading)loading.hidden=true;if(content)content.hidden=true;if(errorBox){errorBox.hidden=false;errorBox.innerHTML=`<i class="fa-solid fa-circle-exclamation"></i> ${esc(msg)}`;}};
  const loadOrder=async()=>{const r=await window.sb.from("orders").select("*").eq("id",orderId).maybeSingle();if(r.error)throw r.error;if(!r.data)throw new Error("Order tidak ditemukan atau tidak dapat diakses.");return r.data;};
  const renderStatus=status=>{const s=String(status||"pending").toLowerCase();$("paymentStatusPill").textContent=s.toUpperCase();const title=$("paymentStatusTitle"),text=$("paymentStatusText"),icon=$("statusIcon");if(["paid","success","completed"].includes(s)){icon.innerHTML='<i class="fa-solid fa-circle-check"></i>';title.textContent="Pembayaran berhasil";text.textContent="Pembayaran sudah diverifikasi.";clearInterval(timer);setTimeout(()=>location.href=`payment-success.html?order_id=${encodeURIComponent(orderId)}`,500);return true;}if(["failed","cancelled","canceled","expired"].includes(s)){icon.innerHTML='<i class="fa-solid fa-circle-xmark"></i>';title.textContent="Pembayaran tidak berhasil";text.textContent="Order ini tidak lagi dapat dibayar.";clearInterval(timer);return false;}icon.innerHTML='<i class="fa-solid fa-clock"></i>';title.textContent="Menunggu pembayaran";text.textContent="Scan QRIS Bayar.gg. Status akan diverifikasi otomatis.";return false;};
  const loadQr=()=>new Promise((resolve,reject)=>{if(window.QRCode)return resolve();const s=document.createElement("script");s.src="https://cdn.jsdelivr.net/npm/qrcodejs@1.0.0/qrcode.min.js";s.onload=resolve;s.onerror=()=>reject(new Error("Library QR tidak dapat dimuat."));document.head.appendChild(s);});
  const createPayment=async order=>{if(creating)return;creating=true;try{qr.innerHTML='<div class="qr-loading"><i class="fa-solid fa-spinner fa-spin"></i><span>Membuat QRIS Bayar.gg...</span></div>';if(!window.sb)throw new Error("Supabase client belum siap.");const r=await window.sb.functions.invoke("create-bayargg-payment",{body:{order_id:order.id}});if(r.error){let msg=r.error.message||"Gagal menghubungi Edge Function pembayaran.";try{const b=await r.error.context?.json?.();msg=b?.error||b?.message||msg;}catch{}throw new Error(msg);}const p=r.data?.data||r.data||{};if(p.success===false)throw new Error(p.error||p.message||"Bayar.gg gagal membuat pembayaran.");const qris=String(p.qris_string||"").trim(),paymentUrl=String(p.payment_url||"").trim();if(qris){await loadQr();qr.innerHTML='<div class="qr-title"><i class="fa-solid fa-qrcode"></i><span>Scan QRIS Bayar.gg</span></div><div id="bayarggQr" class="bayargg-qr"></div><small class="qr-hint">Scan menggunakan aplikasi bank atau e-wallet kamu.</small>';new QRCode($("bayarggQr"),{text:qris,width:240,height:240,colorDark:"#111827",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.M});}else if(paymentUrl){qr.innerHTML='<div class="qr-loading"><i class="fa-solid fa-arrow-up-right-from-square"></i><span>QR tidak tersedia. Gunakan halaman pembayaran.</span></div>';}else throw new Error("Bayar.gg tidak mengembalikan QRIS atau payment URL.");if(paymentUrl){urlBtn.hidden=false;urlBtn.href=paymentUrl;urlBtn.textContent="Buka Pembayaran Bayar.gg";}}finally{creating=false;}};
  const checkGatewayStatus=async()=>{const r=await window.sb.functions.invoke("check-bayargg-payment",{body:{order_id:orderId}});if(r.error)throw r.error;return r.data?.data||r.data||null;};
  try{const user=await window.TC?.user?.().catch(()=>null);if(!user){location.href=`login.html?redirect=${encodeURIComponent(location.href)}`;return;}if(!orderId)throw new Error("order_id tidak ditemukan.");const order=await loadOrder();$("orderId").textContent=order.id;$("orderAmount").textContent=money(order.amount);$("orderTitle").textContent=order.item_title||"PasTele Order";$("orderType").textContent=String(order.item_type||"Pembayaran").replace(/_/g," ");$("copyOrder").onclick=()=>navigator.clipboard?.writeText(String(order.id)).then(()=>window.TC?.toast?.("Order ID disalin.","success"));content.hidden=false;loading.hidden=true;if(renderStatus(order.status))return;if(!["failed","cancelled","canceled","expired"].includes(String(order.status||"").toLowerCase()))await createPayment(order);const poll=async()=>{const latest=await loadOrder();if(renderStatus(latest.status))return;const g=await checkGatewayStatus().catch(()=>null);if(g?.status)renderStatus(String(g.status).toLowerCase()==="paid"?"paid":latest.status);};timer=setInterval(poll,5000);check.onclick=async()=>{check.disabled=true;try{await poll();window.TC?.toast?.("Status pembayaran diperbarui.","success");}catch(e){window.TC?.toast?.(e?.message||"Gagal mengecek status.","error");}finally{check.disabled=false;}};window.addEventListener("beforeunload",()=>clearInterval(timer));}catch(e){console.error("[PasTele Payment]",e);fail(e?.message||"Pembayaran gagal disiapkan.");}
});
