document.addEventListener('DOMContentLoaded', async () => {
 const qs=new URLSearchParams(location.search),id=qs.get('id'),type=(qs.get('type')||'link').toLowerCase(),box=document.getElementById('content');
 const icon=t=>t==='code'?'fa-code':t==='channel'?'fa-broadcast-tower':t==='group'?'fa-users':'fa-link';
 if(!id){box.innerHTML='<div class="empty">Produk tidak ditemukan.</div>';return}
 const {data:x,error}=await sb.rpc('get_market_item_detail',{p_type:type,p_id:id});
 if(error||!x){box.innerHTML=`<div class="empty">${TC.esc(error?.message||'Produk tidak ditemukan atau belum dipublikasikan.')}</div>`;return}
 try{await sb.rpc('record_content_view',{p_owner:x.owner_id,p_target_type:type,p_target_id:id})}catch(_){ }
 const price=Number(x.price||0),canAccess=x.can_access===true,content=canAccess?(x.content||x.description||'Tidak ada detail.'):price>0?'Konten berbayar. Bayar sesuai nominal untuk membuka akses.':(x.description||'Tidak ada detail.');
 box.innerHTML=`<article class="product-detail"><div class="product-detail-icon"><i class="fa-solid ${icon(type)}"></i></div><span class="badge">${TC.esc(String(x.access_type||'free').toUpperCase())}</span><h1>${TC.esc(x.title||'Untitled')}</h1><p class="muted">Oleh <b>${TC.esc(x.creator_name||'Creator')}</b> · ${Number(x.views||0).toLocaleString('id-ID')} views</p><div class="detail-body">${canAccess?content:TC.esc(content)}</div><div class="detail-actions"><button class="btn" id="like"><i class="fa-regular fa-heart"></i> Like</button><button class="btn" id="share"><i class="fa-solid fa-share-nodes"></i> Share</button><b class="price">${price?TC.money(price):'FREE'}</b><button class="btn primary" id="buy">${canAccess?'<i class="fa-solid fa-circle-check"></i> Sudah diakses':price?'<i class="fa-solid fa-qrcode"></i> Bayar via Cashi QRIS':'<i class="fa-solid fa-unlock"></i> Ambil akses'}</button></div></article>`;
 const buy=document.getElementById('buy');if(canAccess)buy.disabled=true;
 buy.onclick=async()=>{const u=await TC.user();if(!u)return location.href='login.html';if(!price){const q=await sb.rpc('buy_market_item',{p_type:type,p_id:id});if(q.error)return TC.toast(q.error.message,'error');TC.toast('Akses berhasil dibuka','success');return setTimeout(()=>location.reload(),500)}
   buy.disabled=true;buy.innerHTML='<i class="fa-solid fa-spinner fa-spin"></i> Menyiapkan QR...';
   try{const o=await sb.rpc('create_checkout_order',{p_type:type,p_id:id});if(o.error)throw o.error;const order=o.data;const cfg=window.PASTELE_CONFIG||{};const token=cfg.SUPABASE_ANON_KEY;const url=(cfg.SUPABASE_URL||'').replace(/\/$/,'')+'/functions/v1/create-cashi-payment';const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({order_id:order.order_id,amount:Number(order.amount),title:order.title})});const payload=await r.json().catch(()=>({}));if(!r.ok)throw new Error(payload.error||'Gateway Cashi belum tersedia');showPaymentModal(order,payload)}catch(e){TC.toast(e.message||'Pembayaran gagal dibuat','error');buy.disabled=false;buy.innerHTML='<i class="fa-solid fa-qrcode"></i> Bayar via Cashi QRIS'}
 };
 document.getElementById('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href)}catch(_){}try{await sb.rpc('track_analytics',{p_owner:x.owner_id,p_event:'share',p_target_type:type,p_target_id:id})}catch(_){}TC.toast('Link berhasil disalin','success')};
 document.getElementById('like').onclick=async()=>{const r=await sb.rpc('toggle_content_like',{p_owner:x.owner_id,p_target_type:type,p_target_id:id});if(r.error)return TC.toast(r.error.message,'error');document.getElementById('like').innerHTML=r.data?.liked?'<i class="fa-solid fa-heart"></i> Liked':'<i class="fa-regular fa-heart"></i> Like'};
 function showPaymentModal(order,pay){const old=document.getElementById('cashiModal');old?.remove();const m=document.createElement('div');m.className='cashi-modal-backdrop';m.id='cashiModal';m.innerHTML=`<div class="cashi-modal"><button class="cashi-close" type="button">×</button><span class="badge">CASHI · QRIS</span><h2>Bayar ${TC.money(order.amount)}</h2><p class="muted">Nominal pembayaran dikunci sesuai harga produk.</p><div class="cashi-qr">${pay.qr_image?`<img src="${TC.esc(pay.qr_image)}" alt="QRIS Cashi">`:pay.qr_string?`<div class="qr-text">${TC.esc(pay.qr_string)}</div>`:'<div class="empty">QR belum diterima dari Cashi.</div>'}</div>${pay.payment_url?`<a class="btn primary" target="_blank" rel="noopener" href="${TC.esc(pay.payment_url)}">Buka pembayaran Cashi</a>`:''}<p class="cashi-status" id="cashiStatus">Menunggu pembayaran...</p></div>`;document.body.appendChild(m);m.querySelector('.cashi-close').onclick=()=>m.remove();if(pay.order_id||order.order_id)poll(order.order_id,m)}
 async function poll(orderId,m){const timer=setInterval(async()=>{try{const r=await sb.from('orders').select('status,payment_id,paid_at').eq('id',orderId).maybeSingle();if(r.data?.status==='paid'){clearInterval(timer);m.querySelector('#cashiStatus').textContent='Pembayaran berhasil. Membuka akses...';setTimeout(()=>location.reload(),700)}else if(r.data?.status==='expired'){clearInterval(timer);m.querySelector('#cashiStatus').textContent='Pembayaran kedaluwarsa.'}}catch(_){ }},2500);setTimeout(()=>clearInterval(timer),30*60*1000)}
});
