document.addEventListener('DOMContentLoaded',async()=>{
 const p=new URLSearchParams(location.search),id=p.get('id'),type=p.get('type')||'link',box=document.getElementById('content');
 if(!id)return box.innerHTML='<div class="empty">Produk tidak ditemukan.</div>';
 const {data:x,error}=await sb.from('marketplace_public').select('*').eq('id',id).eq('type',type).maybeSingle();
 if(error||!x)return box.innerHTML='<div class="empty">Produk tidak ditemukan atau belum dipublikasikan.</div>';
 try{await sb.rpc('record_content_view',{p_owner:x.owner_id,p_target_type:type,p_target_id:id})}catch(_){}
 const followTarget=x.creator_username?`<button class="btn" id="follow"><i class="fa-solid fa-user-plus"></i> Follow creator</button>`:'';
 box.innerHTML=`<article class="product-detail"><div class="product-detail-icon"><i class="fa-solid ${type==='code'?'fa-code':type==='channel'?'fa-broadcast-tower':type==='group'?'fa-users':'fa-link'}"></i></div><span class="badge">${TC.esc(String(x.access_type||'free').toUpperCase())}</span><h1>${TC.esc(x.title)}</h1><p class="muted">Oleh <b>${TC.esc(x.creator_name||'Creator')}</b> · ${Number(x.views||0).toLocaleString('id-ID')} views</p><div class="detail-body">${x.content||x.description||'Tidak ada detail.'}</div><div class="detail-actions"><button class="btn" id="like"><i class="fa-regular fa-heart"></i> Like</button><button class="btn" id="share"><i class="fa-solid fa-share-nodes"></i> Share</button>${followTarget}<b class="price">${Number(x.price||0)?TC.money(x.price):'FREE'}</b><button class="btn primary" id="buy"><i class="fa-solid fa-cart-shopping"></i> ${Number(x.price||0)?'Beli sekarang':'Ambil akses'}</button></div></article>`;
 document.getElementById('buy').onclick=async()=>{const u=await TC.user();if(!u)return location.href='login.html';if(!confirm(Number(x.price||0)?`Beli ${x.title} seharga ${TC.money(x.price)} dari saldo wallet?`:`Ambil ${x.title}?`))return;const q=await sb.rpc('buy_market_item',{p_type:type,p_id:id});if(q.error)TC.toast(q.error.message,'error');else{TC.toast('Pembelian berhasil','success');setTimeout(()=>location.href='purchases.html',500)}};
 document.getElementById('share').onclick=async()=>{try{await navigator.clipboard.writeText(location.href)}catch(_){};try{await sb.rpc('track_analytics',{p_owner:x.owner_id||null,p_event:'share',p_target_type:type,p_target_id:id})}catch(_){};TC.toast('Link berhasil dibagikan')};
 document.getElementById('like').onclick=async()=>{try{const r=await sb.rpc('toggle_content_like',{p_owner:x.owner_id||null,p_target_type:type,p_target_id:id});document.getElementById('like').innerHTML=r.data?.liked?'<i class="fa-solid fa-heart"></i> Liked':'<i class="fa-regular fa-heart"></i> Like'}catch(e){TC.toast(e.message,'error')}};
 document.getElementById('follow')?.addEventListener('click',async()=>{try{const r=await sb.rpc('toggle_creator_follow',{p_creator:x.owner_id});document.getElementById('follow').innerHTML=r.data?.following?'<i class="fa-solid fa-user-check"></i> Following':'<i class="fa-solid fa-user-plus"></i> Follow creator'}catch(e){TC.toast(e.message,'error')}});
});