document.addEventListener('DOMContentLoaded',async()=>{
 const p=await TC.profile();if(!p)return location.replace('login.html');const $=id=>document.getElementById(id);
 const name=p.display_name||p.username||'User';$('name').textContent=name;$('avatar').textContent=name.slice(0,1).toUpperCase();$('bio').textContent=p.bio||'Kelola identitas dan kontenmu.';
 const esc=TC.esc;
 $('details').innerHTML=[['Username',p.username],['Username Telegram',p.telegram_username||'Belum diisi'],['No. WhatsApp',p.whatsapp_number||'Belum diisi'],['Gmail',p.auth_email],['Website',p.website||'Belum diisi'],['Role',p.role||'user']].map(x=>`<div class="detail-row"><small>${esc(x[0])}</small><b>${esc(x[1]||'-')}</b></div>`).join('');
 const [pa,c,ch,pr]=await Promise.all([sb.from('pastelinks').select('id',{count:'exact',head:true}).eq('user_id',p.id),sb.from('telegram_products').select('id',{count:'exact',head:true}).eq('owner_id',p.id),sb.from('telegram_channels').select('id',{count:'exact',head:true}).eq('owner_id',p.id),sb.from('products').select('id',{count:'exact',head:true}).eq('creator_id',p.id)]);
 $('counts').innerHTML=[['fa-link','Pastelink',pa.count||0],['fa-code','Code',c.count||0],['fa-broadcast-tower','Channel / Group',ch.count||0],['fa-box','Marketplace product',pr.count||0]].map(x=>`<a class="content-count" href="my-products.html"><span><i class="fa-solid ${x[0]}"></i> ${x[1]}</span><b>${x[2]}</b></a>`).join('');
 $('profilePass').onsubmit=async e=>{e.preventDefault();const v=$('profileNewPass').value;if(v.length<6)return TC.toast('Password minimal 6 karakter','error');const r=await sb.auth.updateUser({password:v});TC.toast(r.error?.message||'Password berhasil diubah',r.error?'error':'success');if(!r.error)e.target.reset()};$('profilePassToggle').onclick=()=>{const i=$('profileNewPass');i.type=i.type==='password'?'text':'password';$('profilePassToggle').innerHTML=`<i class="fa-solid ${i.type==='password'?'fa-eye':'fa-eye-slash'}"></i>`};
 const admin=p.is_admin===true||p.role==='admin';if(!admin) $('adminBtn').style.display='none';
 try{const r=await sb.rpc('get_login_info');$('currentLogin').textContent=r.data?.current?.logged_in_at?new Date(r.data.current.logged_in_at).toLocaleString('id-ID'):'Belum tercatat';$('lastLogin').textContent=r.data?.last?.logged_in_at?new Date(r.data.last.logged_in_at).toLocaleString('id-ID'):'Belum ada'}catch(_){}
});