
/* SOURCE: /js/settings-fixed.js?v=20260831-final */
document.addEventListener('DOMContentLoaded',async()=>{
 const p=await TC.profile();if(!p)return location.replace('login.html');const $=id=>document.getElementById(id);const adminBtn=$('adminBtn');if(adminBtn)adminBtn.style.display=(p.is_admin===true||p.role==='admin')?'inline-flex':'none';$('username').value=p.username||'';$('telegram_username').value=p.telegram_username||'';$('whatsapp_number').value=p.whatsapp_number||'';$('bio').value=p.bio||'';$('email').textContent=p.auth_email||'';
 const providers={ewallet:{ID:['DANA','OVO','GoPay','ShopeePay','LinkAja','iSaku','Sakuku','Jenius Pay','QRIS'],US:['PayPal','Venmo','Cash App','Apple Pay','Google Pay'],GB:['PayPal','Revolut','Wise'],SG:['PayNow','GrabPay','PayPal'],MY:['Touch n Go eWallet','GrabPay','Boost','PayPal'],PH:['GCash','Maya','GrabPay'],TH:['TrueMoney','Rabbit LINE Pay'],AU:['PayPal','Apple Pay','Google Pay'],JP:['PayPay','LINE Pay','Rakuten Pay'],OTHER:['PayPal','Wise','Revolut']},bank:{ID:['BCA','BRI','BNI','Mandiri','BSI','CIMB Niaga','Danamon','Permata','BTN','Bank Jago','SeaBank','Bank Neo Commerce','Maybank Indonesia'],US:['JPMorgan Chase','Bank of America','Wells Fargo','Citibank','U.S. Bank','Capital One'],GB:['HSBC UK','Barclays','Lloyds Bank','NatWest','Santander UK'],SG:['DBS','OCBC','UOB','Standard Chartered Singapore'],MY:['Maybank','CIMB Malaysia','Public Bank','RHB','Hong Leong Bank'],PH:['BDO','BPI','Metrobank','UnionBank','Security Bank'],TH:['Bangkok Bank','Kasikornbank','Krungthai','Siam Commercial Bank'],AU:['Commonwealth Bank','ANZ','Westpac','NAB'],JP:['MUFG','SMBC','Mizuho','Japan Post Bank'],OTHER:['SWIFT / International Bank']}};
 let method='ewallet';function fill(){const arr=providers[method][$('country').value]||providers[method].OTHER;$('provider').innerHTML=arr.map(x=>`<option>${TC.esc(x)}</option>`).join('')}fill();document.querySelectorAll('[data-method]').forEach(b=>b.onclick=()=>{method=b.dataset.method;document.querySelectorAll('[data-method]').forEach(x=>x.classList.toggle('active',x===b));fill()});$('country').onchange=fill;
 $('profileForm').onsubmit=async e=>{e.preventDefault();const r=await sb.from('profiles').update({username:$('username').value.trim(),display_name:$('username').value.trim(),telegram_username:$('telegram_username').value.trim()||null,whatsapp_number:$('whatsapp_number').value.trim()||null,bio:$('bio').value.trim()||null,updated_at:new Date().toISOString()}).eq('id',p.id);TC.toast(r.error?.message||'Profil berhasil disimpan',r.error?'error':'success')};
 $('passForm').onsubmit=async e=>{e.preventDefault();const r=await sb.auth.updateUser({password:$('newpass').value});TC.toast(r.error?.message||'Password berhasil diubah',r.error?'error':'success');if(!r.error)e.target.reset()};
 document.querySelectorAll('[data-toggle-pass]').forEach(b=>b.onclick=()=>{const i=$(b.dataset.togglePass);i.type=i.type==='password'?'text':'password';b.innerHTML=`<i class="fa-solid ${i.type==='password'?'fa-eye':'fa-eye-slash'}"></i>`});
 $('payForm').onsubmit=async e=>{e.preventDefault();const r=await sb.from('payment_methods').insert({user_id:p.id,method_type:method,provider:$('provider').value,account_name:$('pname').value.trim(),account_number:$('pnumber').value.trim(),country:$('country').value});if(r.error)TC.toast(r.error.message,'error');else{TC.toast('Payment tersimpan','success');e.target.reset();fill();loadPayments()}};
 async function loadPayments(){const r=await sb.from('payment_methods').select('*').eq('user_id',p.id).order('created_at',{ascending:false});$('savedPayments').innerHTML=(r.data||[]).map(x=>`<div class="saved-payment"><div><b>${TC.esc(x.provider)}</b><small>${TC.esc(x.method_type)} · ${TC.esc(x.account_name)} · ${TC.esc(x.account_number)}</small></div><button class="btn" data-del-pay="${x.id}"><i class="fa-solid fa-trash"></i></button></div>`).join('')||'<p class="muted">Belum ada payment tersimpan.</p>';document.querySelectorAll('[data-del-pay]').forEach(b=>b.onclick=async()=>{await sb.from('payment_methods').delete().eq('id',b.dataset.delPay).eq('user_id',p.id);loadPayments()})}loadPayments();$('logout').onclick=()=>Auth.logout();
});
