(()=>{
const D={id:{Notifications:'Notifikasi','No notifications':'Tidak ada notifikasi','Mark all as read':'Tandai semua sudah dibaca'},en:{Notifications:'Notifications','No notifications':'No notifications','Mark all as read':'Mark all as read'}};
const L=()=>localStorage.getItem('telecod_lang')==='en'?'en':'id';
function apply(){document.documentElement.classList.remove('light');document.documentElement.classList.add('dark');document.body?.classList.remove('light');document.body?.classList.add('dark');document.documentElement.dataset.theme='dark';document.documentElement.lang=L();}
function tr(){document.querySelectorAll('[data-i18n]').forEach(e=>{const k=e.dataset.i18n;if(D[L()]?.[k])e.textContent=D[L()][k]})}
window.TeleCodUI={lang:L,apply,setLang(v){localStorage.setItem('telecod_lang',v==='en'?'en':'id');tr()}};
function bell(){if(document.querySelector('.telecod-notification'))return;const h=document.querySelector('[data-notification-host]')||document.querySelector('.topbar');if(!h)return;const b=document.createElement('div');b.className='telecod-notification';b.innerHTML='<button class="telecod-notification-btn" aria-label="Notifications"><i class="fa-regular fa-bell"></i><b class="telecod-notification-badge" hidden>0</b></button><div class="telecod-notification-panel" hidden><div class="telecod-notification-head"><strong>Notifications</strong><button class="telecod-mark-read">Mark all as read</button></div><div class="telecod-notification-list"></div></div>';h.appendChild(b);const panel=b.querySelector('.telecod-notification-panel');b.querySelector('.telecod-notification-btn').onclick=()=>panel.hidden=!panel.hidden;document.addEventListener('click',e=>{if(!b.contains(e.target))panel.hidden=true});b.querySelector('.telecod-mark-read').onclick=()=>{localStorage.setItem('telecod_notifications_seen',String(Date.now()));window.TeleCodNotifications?.refresh()};window.TeleCodNotifications={toggle(){panel.hidden=!panel.hidden},refresh(){const a=JSON.parse(localStorage.getItem('telecod_notifications')||'[]');const seen=Number(localStorage.getItem('telecod_notifications_seen')||0);const unread=a.filter(x=>Number(x.ts||0)>seen);const badge=b.querySelector('.telecod-notification-badge');badge.hidden=!unread.length;badge.textContent=unread.length>99?'99+':unread.length;b.querySelector('.telecod-notification-list').innerHTML=a.length?a.slice(0,30).map(n=>`<div class="telecod-notification-item"><div><span class="telecod-notification-icon"><i class="fa-solid ${n.icon||'fa-bell'}"></i></span><b>${String(n.title||'TeleCod').replace(/[<>]/g,'')}</b></div><small>${String(n.message||'').replace(/[<>]/g,'')}</small><time>${new Date(n.ts||Date.now()).toLocaleString('id-ID',{dateStyle:'short',timeStyle:'short'})}</time></div>`).join(''):`<div class="telecod-empty">${D[L()]['No notifications']}</div>`}};window.TeleCodNotifications.refresh()}
document.addEventListener('DOMContentLoaded',()=>{apply();tr();bell()});
})();
