document.addEventListener('DOMContentLoaded',async()=>{
 const p=await TC.profile();if(!p)return location.replace('login.html');const $=id=>document.getElementById(id);
 const wq=await sb.from('wallets').select('*').eq('user_id',p.id).maybeSingle(),w=wq.data;
 const rq=await sb.from('withdrawals').select('*').eq('user_id',p.id).order('created_at',{ascending:false}).limit(100),rows=rq.data||[];
 $('bal').textContent=TC.money(w?.available_balance??w?.balance??p.balance);$('req').textContent=TC.money(rows.filter(x=>['pending','processing'].includes(x.status)).reduce((n,x)=>n+Number(x.total_debit||x.amount||0),0));$('done').textContent=TC.money(rows.filter(x=>['completed','paid','success'].includes(x.status)).reduce((n,x)=>n+Number(x.amount||0),0));
 const today=rows.filter(x=>new Date(x.created_at).toDateString()===new Date().toDateString()).reduce((n,x)=>n+Number(x.amount||0),0),pct=Math.min(100,today/500000*100),bar=$('dailyBar');bar.style.width=pct+'%';bar.dataset.level=pct>=100?'full':pct>=50?'half':'low';$('dailyText').textContent=TC.money(today)+' / '+TC.money(500000);
 const saved=await sb.from('payment_methods').select('*').eq('user_id',p.id).order('created_at',{ascending:false});const methods=saved.data||[];
 $('instantBtns').innerHTML=[50000,100000,150000,200000,250000].map(n=>`<button type="button" class="btn instant-choice" data-a="${n}"><i class="fa-solid fa-bolt"></i> ${TC.money(n)}</button>`).join('');$('method').innerHTML=['ewallet','bank'].map(x=>`<option value="${x}">${x==='ewallet'?'E-Wallet':'Bank'}</option>`).join('');
 function choose(n){$('amount').value=n;$('mode').value='instant';$('wd').querySelector('button[type=submit]').innerHTML='<i class="fa-solid fa-bolt"></i> Withdraw Instan';$('amount').focus()}
 document.querySelectorAll('.instant-choice').forEach(b=>b.onclick=()=>choose(Number(b.dataset.a)));
 const wrap=document.createElement('div');wrap.className='saved-withdraw';wrap.innerHTML='<b><i class="fa-solid fa-bookmark"></i> Payment tersimpan</b>'+methods.map(x=>`<button type="button" class="btn" data-method-id="${x.id}">${TC.esc(x.provider)} · ${TC.esc(x.account_number)}</button>`).join('');$('wd').prepend(wrap);wrap.querySelectorAll('[data-method-id]').forEach(b=>b.onclick=()=>{const x=methods.find(m=>m.id===b.dataset.methodId);$('method').value=x.method_type;$('aname').value=x.account_name;$('anum').value=x.account_number});
 $('mode').onchange=()=>{$('wd').querySelector('button[type=submit]').innerHTML=$('mode').value==='instant'?'<i class="fa-solid fa-bolt"></i> Withdraw Instan':'<i class="fa-solid fa-paper-plane"></i> Ajukan penarikan'};
 $('wd').onsubmit=async e=>{e.preventDefault();const a=Number($('amount').value);if(!a)return TC.toast('Nominal wajib diisi','error');if($('mode').value==='manual'&&a<100000)return TC.toast('Manual minimum Rp100.000','error');if($('mode').value==='instant'&&a>250000)return TC.toast('Instant maksimum Rp250.000','error');if(a>(Number(w?.available_balance??w?.balance??0)))return TC.toast('Saldo tidak mencukupi','error');try{const r=await sb.rpc('request_withdrawal_v2',{p_amount:a,p_mode:$('mode').value,p_method:$('method').value,p_account_name:$('aname').value,p_account_number:$('anum').value});if(r.error)throw r.error;TC.toast('Withdraw berhasil diajukan','success');setTimeout(()=>location.reload(),600)}catch(e){TC.toast(e.message,'error')}};
 $('history').innerHTML=rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('id-ID')}</td><td>${TC.money(x.amount)}</td><td><i class="fa-solid ${x.method==='bank'?'fa-building-columns':'fa-wallet'}"></i> ${TC.esc(x.method)}<br><small>${TC.esc(x.account_number||'')}</small></td><td>${TC.esc(x.mode)}</td><td>${TC.esc(x.status)}</td><td>${TC.esc(x.ticket_code||x.id)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada pengajuan.</td></tr>';
});