document.addEventListener('DOMContentLoaded',async()=>{
 const p=await TC.profile();if(!p)return location.replace('login.html');const $=id=>document.getElementById(id);
 const wq=await sb.from('wallets').select('*').eq('user_id',p.id).maybeSingle(),w=wq.data;const balance=Number(w?.available_balance??w?.balance??p.balance??0);
 const rq=await sb.from('withdrawals').select('*').eq('user_id',p.id).order('created_at',{ascending:false}).limit(100),rows=rq.data||[];
 $('bal').textContent=TC.money(balance);$('req').textContent=TC.money(rows.filter(x=>['pending','processing'].includes(String(x.status).toLowerCase())).reduce((n,x)=>n+Number(x.total_debit||x.amount||0),0));$('done').textContent=TC.money(rows.filter(x=>['completed','paid','success'].includes(String(x.status).toLowerCase())).reduce((n,x)=>n+Number(x.amount||0),0));
 const today=rows.filter(x=>new Date(x.created_at).toDateString()===new Date().toDateString()).reduce((n,x)=>n+Number(x.amount||0),0),pct=Math.min(100,today/500000*100);$('dailyBar').style.width=pct+'%';$('dailyText').textContent=TC.money(today)+' / '+TC.money(500000);
 const saved=await sb.from('payment_methods').select('*').eq('user_id',p.id).order('created_at',{ascending:false}),methods=saved.data||[];
 $('instantBtns').innerHTML=[50000,100000,150000,200000,250000].map(n=>`<button type="button" class="btn instant-choice" data-a="${n}"><i class="fa-solid fa-bolt"></i> ${TC.money(n)}</button>`).join('');
 const wrap=document.createElement('div');wrap.className='saved-withdraw';wrap.innerHTML='<b><i class="fa-solid fa-bookmark"></i> Payment tersimpan</b>'+methods.map(x=>`<button type="button" class="btn" data-method-id="${x.id}">${TC.esc(x.provider)} · ${TC.esc(x.account_number)}</button>`).join('');document.getElementById('wd').prepend(wrap);
 let selected=methods[0]||null; if(selected){$('method').value=selected.method_type;$('aname').value=selected.account_name;$('anum').value=selected.account_number}
 wrap.querySelectorAll('[data-method-id]').forEach(b=>b.onclick=()=>{selected=methods.find(m=>m.id===b.dataset.methodId);if(selected){$('method').value=selected.method_type;$('aname').value=selected.account_name;$('anum').value=selected.account_number}});
 async function request(amount,mode){if(!amount)return TC.toast('Nominal wajib diisi','error');if(mode==='instant'&&amount>250000)return TC.toast('Instant maksimum Rp250.000','error');if(mode==='instant'&&today+amount>500000)return TC.toast('Batas WD instant harian Rp500.000 tercapai','error');if(mode==='manual'&&amount<100000)return TC.toast('Manual minimum Rp100.000','error');if(amount>balance)return TC.toast('Saldo tidak mencukupi','error');if(!$('aname').value.trim()||!$('anum').value.trim())return TC.toast('Isi metode penarikan di Settings terlebih dahulu','error');try{const r=await sb.rpc('request_withdrawal_v2',{p_amount:amount,p_mode:mode,p_method:$('method').value,p_account_name:$('aname').value.trim(),p_account_number:$('anum').value.trim()});if(r.error)throw r.error;TC.toast(mode==='instant'?'WD Instant berhasil diajukan':'WD Manual berhasil diajukan','success');setTimeout(()=>location.reload(),650)}catch(e){TC.toast(e.message||'Withdraw gagal','error')}}
 document.querySelectorAll('.instant-choice').forEach(b=>b.onclick=()=>request(Number(b.dataset.a),'instant'));$('instantSubmit').onclick=()=>{const b=document.querySelector('.instant-choice.selected')||document.querySelector('.instant-choice');document.querySelectorAll('.instant-choice').forEach(x=>x.classList.remove('selected'));b?.classList.add('selected');request(Number(b?.dataset.a||50000),'instant')};
 $('wd').onsubmit=e=>{e.preventDefault();request(Number($('amount').value),'manual')};$('urgent').onclick=()=>TC.toast('Request mendadak dikirim ke admin','success');
 $('history').innerHTML=rows.map(x=>`<tr><td>${new Date(x.created_at).toLocaleString('id-ID')}</td><td>${TC.money(x.amount)}</td><td><i class="fa-solid ${x.method==='bank'?'fa-building-columns':'fa-wallet'}"></i> ${TC.esc(x.method||'-')}<br><small>${TC.esc(x.account_number||'')}</small></td><td>${TC.esc(x.mode||'manual')}</td><td>${TC.esc(x.status||'-')}</td><td>${TC.esc(x.ticket_code||x.id)}</td></tr>`).join('')||'<tr><td colspan="6" class="empty">Belum ada pengajuan.</td></tr>';
});
