window.TC_I18N={id:{title:'Checkout',status:'Status pesanan',payment:'Pembayaran',waiting:'Menunggu pembayaran…',paid:'Pembayaran berhasil.',openPay:'Buka QR / Checkout BAYAR GG',check:'Cek Status',back:'Kembali ke Marketplace',delivery:'Code & Cara Pasang',fee:'20% fee platform • creator menerima 80% H+1'},en:{title:'Checkout',status:'Order status',payment:'Payment',waiting:'Waiting for payment…',paid:'Payment successful.',openPay:'Open BAYAR GG Checkout',check:'Check Status',back:'Back to Marketplace',delivery:'Code & Setup Guide',fee:'20% platform fee • creator receives 80% H+1'}};
const sb=supabase.createClient(TELECOD_CONFIG.SUPABASE_URL,TELECOD_CONFIG.SUPABASE_ANON_KEY),id=new URLSearchParams(location.search).get('id');let order=null;
function esc(v){return tcEscape(v)}
async function load(){const box=document.getElementById('box');const {data,error}=await sb.from('orders').select('id,amount,status,payment_url,payment_reference,products(title,description)').eq('id',id).single();if(error||!row){box.innerHTML='<div class="error">Order not found.</div>';return}order=data;render()}
async function reveal(){const {data,error}=await sb.rpc('get_paid_delivery',{p_order_id:order.id}); const row=Array.isArray(data)?data[0]:data;if(error||!row){document.getElementById('delivery').innerHTML='<div class="pending-banner">Payment confirmed, delivery is being prepared.</div>';return}const p=row||{};document.getElementById('delivery').innerHTML=`<div class="card" style="margin-top:16px"><span class="kicker">${tcT('delivery')}</span><h2>${esc(p.title||order.products?.title||'')}</h2>${p.code_content?`<textarea readonly style="width:100%;min-height:280px;margin-top:10px;background:#03070d;color:#eaf6ff;border:1px solid var(--line);border-radius:14px;padding:13px">${esc(p.code_content)}</textarea>`:''}${p.setup_instructions?`<div class="pending-banner"><b>Setup</b><br>${esc(p.setup_instructions).replace(/\n/g,'<br>')}</div>`:''}${row.delivery_url?`<a class="btn primary" target="_blank" rel="noopener" href="${esc(row.delivery_url)}"><i class="fa-solid fa-arrow-up-right-from-square"></i> Open delivery</a>`:''}</div>`}
function render(){let body='';if(order.status==='paid'){body=`<div class="success"><b>${tcT('paid')}</b></div><div class="pending-banner">${tcT('fee')}</div><div id="delivery"></div>`;document.getElementById('box').innerHTML=`<div class="order-product"><span class="kicker">${tcT('status')}</span><h2>${esc(order.products?.title||'')}</h2><div class="order-price">${tcMoney(order.amount)}</div></div>${body}<a class="btn ghost" href="marketplace.html" style="margin-top:14px">${tcT('back')}</a>`;reveal();return}
body=order.payment_url?`<div class="pay-box"><div class="pending-banner"><i class="fa-solid fa-qrcode"></i> BAYAR GG — QRIS & payment methods</div><a class="btn primary xl" target="_blank" rel="noopener" href="${esc(order.payment_url)}"><i class="fa-solid fa-qrcode"></i>${tcT('openPay')}</a><button class="btn ghost" id="refreshPay"><i class="fa-solid fa-rotate"></i>${tcT('check')}</button></div>`:`<div class="pay-box"><p>${tcT('waiting')}</p><button class="btn primary" id="createPay">${tcT('openPay')}</button></div>`;document.getElementById('box').innerHTML=`<div class="order-product"><span class="kicker">${tcT('payment')}</span><h2>${esc(order.products?.title||'')}</h2><p>${esc(order.products?.description||'')}</p><div class="order-price">${tcMoney(order.amount)}</div><span class="status">${esc(order.status)}</span></div>${body}<a class="btn ghost" href="marketplace.html" style="margin-top:14px">${tcT('back')}</a>`;document.getElementById('refreshPay')?.addEventListener('click',load);document.getElementById('createPay')?.addEventListener('click',createPayment)}
async function createPayment(){const b=document.getElementById('createPay');b.disabled=true;try{const {data,error}=await sb.functions.invoke('create-payment',{body:{order_id:order.id}});if(error)throw error;if(data?.payment_url){order.payment_url=data.payment_url;render();}else throw new Error(data?.error||'Payment URL unavailable')}catch(e){document.getElementById('box').insertAdjacentHTML('afterbegin','<div class="error">'+esc(e.message)+'</div>')}finally{b.disabled=false}}
document.addEventListener('DOMContentLoaded',load);window.addEventListener('telecod:language',()=>order&&render());
