
window.TC_I18N={
 id:{market:"Marketplace",features:"Fitur",paste:"PasteLink",how:"Cara Kerja",login:"Login",register:"Daftar",themes:"Terang / Gelap",eyebrow:"DIGITAL TELEGRAM MARKETPLACE",
 hero1:"Punya code & media Telegram?",hero2:"Jadikan aset digitalmu bernilai.",heroDesc:"Jual code, bot, media, PasteLink, dan akses digital melalui satu platform premium. Pembeli bisa menemukan aset, checkout, dan mengelola pembelian dari dashboard.",
 start:"Mulai Sekarang",explore:"Jelajahi Marketplace",secure:"Akses aman",fast:"Pengiriman digital cepat",bilingual:"ID / EN",pasteFloat:"Buat, bagikan & lindungi teks.",
 animeTitle:"Create. Sell. Grow.",animeSub:"Bangun katalog digitalmu.",pasteToolTitle:"Paste, simpan & bagikan",pasteToolDesc:"Buat link teks yang rapi, mudah dibagikan, dan bisa dibuat public, unlisted, atau private.",marketToolTitle:"Cari aset digital",marketToolDesc:"Jelajahi code, bot, media, template, channel VIP, dan produk digital lainnya.",sellToolTitle:"Jual karya kamu",sellToolDesc:"Publish produk dan bagikan halaman produkmu ke komunitas Telegram.",
 products:"Produk",sellers:"Creator",pastes:"PasteLink",available:"Platform",discover:"DISCOVER",marketTitle:"Temukan digital asset yang kamu butuhkan.",viewAll:"Lihat semua →",
 featureTitle:"Dibuat untuk creator digital.",featureDesc:"Satu ekosistem untuk discovery, publishing, PasteLink, dan digital access.",f1t:"Code & Bot",f1:"Listing source code, bot, template, dan aset digital yang legal untuk kamu distribusikan.",f2:"Buat paste publik, unlisted, atau private. Cocok untuk snippet, catatan, konfigurasi, dan teks yang ingin dibagikan.",f3t:"Checkout",f3:"Order tersimpan di database dan akses digital mengikuti status pembayaran.",f4t:"Creator Dashboard",f4:"Kelola produk, harga, order, dan aktivitas akun dari satu dashboard.",
 ageTitle:"Konten digital & komunitas",ageDesc:"TeleCod dapat memuat code, media, bot, dan Channel VIP dari pengguna. Dilarang menjual konten ilegal, hasil curian, malware, kredensial, atau materi yang melanggar hak pihak lain.",
 ctaTitle:"Punya aset digital? Mulai jual hari ini.",ctaDesc:"Daftar, buat produk, bagikan link ke Telegram, YouTube, Facebook, X, atau media lain, lalu kelola order dari dashboard.",registerFree:"Daftar Gratis",footerDesc:"Marketplace digital untuk code, bot, media, PasteLink dan akses digital.",links:"Links",legal:"Legal",terms:"Ketentuan",privacy:"Privasi",rights:"All rights reserved.",
 empty:"Belum ada produk yang dipublish.",howTitle:"Semua kebutuhan digitalmu, satu tempat.",howDesc:"TeleCod dibuat supaya creator bisa membuat, membagikan, menjual, dan mengelola aset digital tanpa UI yang rumit.",how1t:"Buat akun",how1:"Pilih login email/username, Google, atau Telegram. Profil Telegram dapat menyimpan username Telegram sebagai identitas creator.",how2t:"Buat PasteLink",how2:"Tulis teks, kode, konfigurasi, atau catatan. URL seperti https:// dan www. otomatis menjadi link yang dapat diklik saat paste dibuka.",how3t:"Publish & jual",how3:"Masukkan produk ke Marketplace, atur harga, lalu bagikan halaman produk ke Telegram atau platform sosial lain.",how4t:"Kelola & grow",how4:"Pantau produk, order, transaksi, dan aktivitas creator dari dashboard yang responsif di HP maupun desktop.",animeBannerTitle:"Create • Share • Sell • Grow",animeBannerDesc:"Tampilan premium dengan nuansa neon, emoji, dan micro-animation yang bisa terus dipoles sesuai branding TeleCod.",authTitle:"Masuk dengan cara yang kamu suka.",authDesc:"Email/password tetap tersedia, sementara Google dan Telegram memberi akses cepat. Username Telegram juga bisa dipakai sebagai identifier login untuk akun yang sudah memiliki password.",authEmail:"Email / Password",authEmailDesc:"Login dan register standar.",authGoogle:"Google / Gmail",authGoogleDesc:"OAuth Google untuk login cepat.",authTelegram:"Telegram",authTelegramDesc:"Login aman melalui Telegram Login Widget.",authUsername:"Username",authUsernameDesc:"Username Telegram dapat disimpan sebagai identitas akun."},
 en:{market:"Marketplace",features:"Features",paste:"PasteLink",how:"How It Works",login:"Login",register:"Register",themes:"Light / Dark",eyebrow:"DIGITAL TELEGRAM MARKETPLACE",
 hero1:"Have Telegram code & media?",hero2:"Turn your digital assets into value.",heroDesc:"Sell code, bots, media, PasteLinks and digital access from one premium platform. Buyers can discover assets, check out and manage purchases from their dashboard.",
 start:"Get Started",explore:"Explore Marketplace",secure:"Secure access",fast:"Fast digital delivery",bilingual:"EN / ID",pasteFloat:"Create, share & protect your text.",
 animeTitle:"Create. Sell. Grow.",animeSub:"Build your digital catalog.",pasteToolTitle:"Paste, store & share",pasteToolDesc:"Create clean text links that are easy to share and can be public, unlisted or private.",marketToolTitle:"Find digital assets",marketToolDesc:"Explore code, bots, media, templates, VIP channels and other digital products.",sellToolTitle:"Sell your creation",sellToolDesc:"Publish a product and share its product page with your Telegram community.",
 products:"Products",sellers:"Creators",pastes:"PasteLinks",available:"Platform",discover:"DISCOVER",marketTitle:"Find the digital assets you need.",viewAll:"View all →",
 featureTitle:"Built for digital creators.",featureDesc:"One ecosystem for discovery, publishing, PasteLink and digital access.",f1t:"Code & Bot",f1:"List source code, bots, templates and digital assets you are legally allowed to distribute.",f2:"Create public, unlisted or private pastes for snippets, notes, configuration and shareable text.",f3t:"Checkout",f3:"Orders are stored in the database and digital access follows payment status.",f4t:"Creator Dashboard",f4:"Manage products, pricing, orders and account activity from one dashboard.",
 ageTitle:"Digital content & community",ageDesc:"TeleCod may contain code, media, bots and VIP Channels from users. Illegal, stolen, malware, credential or rights-infringing content is prohibited.",
 ctaTitle:"Have a digital asset? Start selling today.",ctaDesc:"Register, create a product, share your link to Telegram, YouTube, Facebook, X or other media, then manage orders from your dashboard.",registerFree:"Register Free",footerDesc:"Digital marketplace for code, bots, media, PasteLinks and digital access.",links:"Links",legal:"Legal",terms:"Terms",privacy:"Privacy",rights:"All rights reserved.",
 empty:"No published products yet.",howTitle:"Everything digital, in one place.",howDesc:"TeleCod is designed so creators can create, share, sell and manage digital assets without a complicated UI.",how1t:"Create an account",how1:"Choose email/username, Google or Telegram. Your Telegram username can be stored as your creator identity.",how2t:"Create a PasteLink",how2:"Write text, code, configuration or notes. URLs such as https:// and www. automatically become clickable links when the paste is opened.",how3t:"Publish & sell",how3:"Publish a product in the Marketplace, set the price and share the product page to Telegram or other social platforms.",how4t:"Manage & grow",how4:"Monitor products, orders, transactions and creator activity from a responsive dashboard on mobile or desktop.",animeBannerTitle:"Create • Share • Sell • Grow",animeBannerDesc:"A premium neon-style interface with emoji and micro-animations that can be polished further for TeleCod branding.",authTitle:"Sign in your way.",authDesc:"Email/password remains available, while Google and Telegram provide fast access. Telegram username can also be used as the login identifier for accounts that have a password.",authEmail:"Email / Password",authEmailDesc:"Standard registration and login.",authGoogle:"Google / Gmail",authGoogleDesc:"Fast Google OAuth login.",authTelegram:"Telegram",authTelegramDesc:"Secure login through Telegram Login Widget.",authUsername:"Username",authUsernameDesc:"Telegram username can be stored as your account identity."}
};
const sb=supabase.createClient(TELECOD_CONFIG.SUPABASE_URL,TELECOD_CONFIG.SUPABASE_ANON_KEY);
async function loadHome(){
 const [p,s,pa]=await Promise.all([
   sb.from("products").select("id,title,slug,price,thumbnail_url,category,status").eq("status","published").order("created_at",{ascending:false}).limit(6),
   sb.from("profiles").select("id",{count:"exact",head:true}),
   sb.from("pastes").select("id",{count:"exact",head:true})
 ]);
 if(!p.error) renderProducts(p.data||[]);
 const sellers=document.getElementById("statSellers"),pastes=document.getElementById("statPastes");
 if(sellers)sellers.textContent=s.count??"0";if(pastes)pastes.textContent=pa.count??"0";
}
function renderProducts(items){
 const el=document.getElementById("products");if(!el)return;
 document.getElementById("statProducts").textContent=items.length;
 if(!items.length){el.innerHTML=`<div class="empty">${tcT("empty")}</div>`;return}
 el.innerHTML=items.map(x=>`<a class="product" href="product.html?slug=${encodeURIComponent(x.slug)}"><div class="thumb">${x.thumbnail_url?`<img src="${tcEscape(x.thumbnail_url)}" alt="">`:'<i class="fa-solid fa-code"></i>'}</div><div class="pbody"><small>${tcEscape(x.category||"Digital")}</small><h3>${tcEscape(x.title)}</h3><b>${tcMoney(x.price)}</b></div></a>`).join("");
}
window.addEventListener("telecod:language",()=>{loadHome()});
document.addEventListener("DOMContentLoaded",loadHome);
