-- ============================================================
-- PasTele / Bdicodebot
-- DATABASE MASTER RESET + FULL RPC
-- DEVELOPMENT RESET ONLY
--
-- IMPORTANT:
-- 1) This resets ONLY public application tables/functions.
-- 2) Supabase auth.users is NOT deleted.
-- 3) Existing public data WILL BE DELETED.
-- 4) Run in Supabase SQL Editor as postgres/service-role.
-- 5) After this SQL, deploy the matching Edge Functions from the ZIP.
-- ============================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- ============================================================
-- DROP APPLICATION FUNCTIONS
-- ============================================================

DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT n.nspname, p.proname,
           pg_get_function_identity_arguments(p.oid) args
    FROM pg_proc p
    JOIN pg_namespace n ON n.oid=p.pronamespace
    WHERE n.nspname='public'
      AND (
        p.proname LIKE 'admin_%'
        OR p.proname IN (
          'buy_market_item','create_account_plan_order',
          'create_checkout_order','get_market_item_detail',
          'get_pending_balance_detail','get_public_site_settings',
          'get_public_workspace_stats','increment_paste_view',
          'record_content_view','release_matured_wallet',
          'request_withdrawal_v2','resolve_username_login',
          'check_username_available','settle_bayargg_order',
          'toggle_content_like','track_analytics','delete_purchase',
          'is_current_user_admin'
        )
      )
  LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS %I.%I(%s) CASCADE',
                   r.nspname,r.proname,r.args);
  END LOOP;
END $$;

-- ============================================================
-- DROP APPLICATION TABLES
-- ============================================================

DROP VIEW IF EXISTS public.profile_public CASCADE;
DROP VIEW IF EXISTS public.marketplace_public CASCADE;

DROP TABLE IF EXISTS public.wallet_transactions CASCADE;
DROP TABLE IF EXISTS public.withdrawals CASCADE;
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.purchases CASCADE;
DROP TABLE IF EXISTS public.payments CASCADE;
DROP TABLE IF EXISTS public.payment_methods CASCADE;
DROP TABLE IF EXISTS public.payment_settings CASCADE;
DROP TABLE IF EXISTS public.product_access CASCADE;
DROP TABLE IF EXISTS public.product_views CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;
DROP TABLE IF EXISTS public.telegram_products CASCADE;
DROP TABLE IF EXISTS public.telegram_channels CASCADE;
DROP TABLE IF EXISTS public.pastelinks CASCADE;
DROP TABLE IF EXISTS public.pastes CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.announcements CASCADE;
DROP TABLE IF EXISTS public.creator_followers CASCADE;
DROP TABLE IF EXISTS public.content_likes CASCADE;
DROP TABLE IF EXISTS public.content_comments CASCADE;
DROP TABLE IF EXISTS public.analytics_events CASCADE;
DROP TABLE IF EXISTS public.code_access_usage CASCADE;
DROP TABLE IF EXISTS public.approved_bots CASCADE;
DROP TABLE IF EXISTS public.bot_integrations CASCADE;
DROP TABLE IF EXISTS public.login_history CASCADE;
DROP TABLE IF EXISTS public.admin_logs CASCADE;
DROP TABLE IF EXISTS public.admins CASCADE;
DROP TABLE IF EXISTS public.site_settings CASCADE;
DROP TABLE IF EXISTS public.site_stats CASCADE;
DROP TABLE IF EXISTS public.wallets CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;

-- ============================================================
-- CORE PROFILES
-- ============================================================

CREATE TABLE public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username text NOT NULL UNIQUE,
  auth_email text NOT NULL,
  display_name text,
  avatar_url text,
  role text NOT NULL DEFAULT 'user',
  is_admin boolean NOT NULL DEFAULT false,
  is_banned boolean NOT NULL DEFAULT false,
  balance numeric(18,2) NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  telegram_username text,
  whatsapp_number text,
  bio text,
  website text,
  country text,
  is_premium boolean NOT NULL DEFAULT false,
  subscription_until timestamptz
);

CREATE TABLE public.admins (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  telegram_id bigint NOT NULL UNIQUE,
  role text NOT NULL DEFAULT 'admin',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.admin_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  admin_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  action text NOT NULL,
  target_id uuid,
  details jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- PRODUCTS / MARKETPLACE
-- ============================================================

CREATE TABLE public.products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  seller_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  creator_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  price numeric(18,2) NOT NULL DEFAULT 0 CHECK (price >= 0),
  thumbnail_url text,
  type text NOT NULL DEFAULT 'link',
  access_type text NOT NULL DEFAULT 'free',
  category text NOT NULL DEFAULT 'General',
  description text DEFAULT '',
  content text DEFAULT '',
  views bigint NOT NULL DEFAULT 0,
  sales_count bigint NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.telegram_products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  type text NOT NULL DEFAULT 'code',
  product_type text,
  access_type text NOT NULL DEFAULT 'free',
  bot_username text,
  telegram_bot_id bigint,
  price numeric(18,2) NOT NULL DEFAULT 0,
  description text DEFAULT '',
  content text DEFAULT '',
  thumbnail_url text,
  category text DEFAULT 'General',
  status text NOT NULL DEFAULT 'draft',
  views bigint NOT NULL DEFAULT 0,
  sales_count bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.telegram_channels (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  username text,
  name text NOT NULL,
  type text NOT NULL DEFAULT 'channel',
  access_type text NOT NULL DEFAULT 'free',
  telegram_channel_id text,
  description text DEFAULT '',
  invite_url text,
  price numeric(18,2) NOT NULL DEFAULT 0,
  category text DEFAULT 'General',
  status text NOT NULL DEFAULT 'draft',
  views bigint NOT NULL DEFAULT 0,
  sales_count bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.purchases (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  buyer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  product_id uuid,
  order_id uuid,
  item_type text,
  item_id text,
  item_title text,
  amount numeric(18,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'completed',
  access_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.orders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  buyer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  seller_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  product_id uuid,
  amount numeric(18,2) NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  item_type text,
  item_id text,
  item_title text,
  payment_reference text,
  paid_at timestamptz,
  gateway_payload jsonb DEFAULT '{}'::jsonb
);

CREATE UNIQUE INDEX orders_payment_reference_uidx
ON public.orders(payment_reference)
WHERE payment_reference IS NOT NULL;

-- ============================================================
-- PASTE / PASTELINK
-- ============================================================

CREATE TABLE public.pastelinks (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  slug text NOT NULL UNIQUE,
  title text NOT NULL,
  content_html text NOT NULL,
  visibility text NOT NULL DEFAULT 'public',
  password_hash text,
  expires_at timestamptz,
  description text DEFAULT '',
  tags text[] DEFAULT '{}'::text[],
  allow_comments boolean DEFAULT true,
  allow_download boolean DEFAULT true,
  show_raw boolean DEFAULT true,
  anonymous boolean DEFAULT false,
  views bigint NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.pastes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  title text NOT NULL,
  slug text NOT NULL UNIQUE,
  content text NOT NULL,
  visibility text NOT NULL DEFAULT 'public',
  password text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- PAYMENT
-- ============================================================

CREATE TABLE public.payment_settings (
  id integer PRIMARY KEY,
  enabled boolean NOT NULL DEFAULT false,
  provider text NOT NULL DEFAULT 'manual',
  mode text NOT NULL DEFAULT 'manual',
  merchant_id text,
  api_endpoint text,
  qr_image_url text,
  instructions text,
  currency text NOT NULL DEFAULT 'IDR',
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.payment_settings(id) VALUES (1)
ON CONFLICT (id) DO NOTHING;

CREATE TABLE public.payment_methods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  method_type text NOT NULL,
  provider text NOT NULL,
  account_name text NOT NULL,
  account_number text NOT NULL,
  country text DEFAULT 'ID',
  is_default boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.payments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid REFERENCES public.orders(id) ON DELETE SET NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  amount numeric(18,2) NOT NULL DEFAULT 0,
  method text,
  reference text,
  status text NOT NULL DEFAULT 'pending',
  created_at timestamptz NOT NULL DEFAULT now(),
  paid_at timestamptz
);

CREATE UNIQUE INDEX payments_reference_uidx
ON public.payments(reference)
WHERE reference IS NOT NULL;

CREATE TABLE public.product_access (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid REFERENCES public.orders(id) ON DELETE CASCADE,
  product_id uuid NOT NULL,
  buyer_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  delivery_url text,
  delivered_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.product_views (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id uuid NOT NULL,
  viewer_hash text,
  created_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- WALLET / TRANSACTIONS
-- ============================================================

CREATE TABLE public.wallets (
  user_id uuid PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  balance numeric(18,2) NOT NULL DEFAULT 0,
  available_balance numeric(18,2) NOT NULL DEFAULT 0,
  pending_balance numeric(18,2) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  amount numeric(18,2) NOT NULL DEFAULT 0,
  fee numeric(18,2) NOT NULL DEFAULT 0,
  net_amount numeric(18,2) NOT NULL DEFAULT 0,
  type text NOT NULL,
  status text NOT NULL DEFAULT 'completed',
  reference text,
  description text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX transactions_reference_uidx
ON public.transactions(user_id, reference)
WHERE reference IS NOT NULL;

CREATE TABLE public.wallet_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  type text NOT NULL,
  amount numeric(18,2) NOT NULL DEFAULT 0,
  balance_before numeric(18,2) NOT NULL DEFAULT 0,
  balance_after numeric(18,2) NOT NULL DEFAULT 0,
  reference text,
  status text NOT NULL DEFAULT 'completed',
  available_at timestamptz,
  settlement_code text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.withdrawals (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  amount numeric(18,2) NOT NULL CHECK (amount > 0),
  fee numeric(18,2) NOT NULL DEFAULT 0 CHECK (fee >= 0),
  net_amount numeric(18,2) NOT NULL DEFAULT 0 CHECK (net_amount >= 0),
  mode text,
  method text,
  account_name text,
  account_number text,
  status text NOT NULL DEFAULT 'pending',
  note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  processed_at timestamptz
);

-- ============================================================
-- SOCIAL / CONTENT / NOTIFICATIONS
-- ============================================================

CREATE TABLE public.creator_followers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  creator_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  follower_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(creator_id,follower_id)
);

CREATE TABLE public.content_likes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  content_owner_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  actor_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  target_id uuid NOT NULL,
  target_type text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(actor_id,target_id,target_type)
);

CREATE TABLE public.content_comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  target_id uuid NOT NULL,
  target_type text NOT NULL DEFAULT 'product',
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  body text DEFAULT '',
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.announcements (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  title text NOT NULL,
  body text NOT NULL DEFAULT '',
  image_url text,
  published boolean NOT NULL DEFAULT false,
  published_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.analytics_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  actor_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  event_type text NOT NULL,
  target_type text,
  target_id uuid,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.code_access_usage (
  user_id uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  usage_date date NOT NULL,
  opens integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(user_id,usage_date)
);

CREATE TABLE public.login_history (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  ip_address inet,
  city text,
  region text,
  country text,
  latitude double precision,
  longitude double precision,
  user_agent text,
  logged_in_at timestamptz NOT NULL DEFAULT now()
);

-- ============================================================
-- BOT / SITE SETTINGS / STATS
-- ============================================================

CREATE TABLE public.approved_bots (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  bot_username text NOT NULL UNIQUE,
  bot_name text,
  bot_id bigint,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.bot_integrations (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  bot_username text,
  telegram_bot_id bigint,
  encrypted_token text,
  is_active boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE public.site_settings (
  id integer PRIMARY KEY,
  settings jsonb NOT NULL DEFAULT '{}'::jsonb,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.site_settings(id) VALUES(1)
ON CONFLICT(id) DO NOTHING;

CREATE TABLE public.site_stats (
  id integer PRIMARY KEY,
  total_users bigint NOT NULL DEFAULT 0,
  total_products bigint NOT NULL DEFAULT 0,
  total_orders bigint NOT NULL DEFAULT 0,
  total_sales numeric(18,2) NOT NULL DEFAULT 0,
  total_revenue numeric(18,2) NOT NULL DEFAULT 0,
  updated_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO public.site_stats(id) VALUES(1)
ON CONFLICT(id) DO NOTHING;

-- ============================================================
-- PUBLIC VIEWS
-- ============================================================

DROP VIEW IF EXISTS public.marketplace_public CASCADE;
DROP VIEW IF EXISTS public.profile_public CASCADE;

CREATE VIEW public.profile_public
WITH (security_invoker = true)
AS
SELECT p.id,p.username,p.display_name,p.avatar_url,p.country,p.created_at
FROM public.profiles AS p
WHERE p.is_banned=false;

CREATE VIEW public.marketplace_public
WITH (security_invoker = true)
AS
SELECT p.id,p.slug,p.title,p.type,p.access_type,p.price,p.thumbnail_url,p.description,p.content,
       p.views,p.sales_count,p.category,p.created_at,
       pr.display_name AS creator_name,pr.username AS creator_username,
       p.creator_id AS owner_id
FROM public.products AS p
LEFT JOIN public.profile_public AS pr
  ON pr.id=COALESCE(p.creator_id,p.seller_id)
WHERE p.status IN ('published','active');

-- ============================================================
-- AUTH PROFILE + WALLET AUTOMATION
-- ============================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  base_username text;
  candidate text;
  n integer := 0;
BEGIN
  base_username := lower(regexp_replace(
    coalesce(new.raw_user_meta_data->>'username',''),
    '[^a-zA-Z0-9_]', '', 'g'
  ));
  IF base_username = '' THEN
    base_username := lower(split_part(coalesce(new.email,'user'),'@',1));
    base_username := regexp_replace(base_username,'[^a-zA-Z0-9_]','','g');
  END IF;
  IF base_username = '' THEN base_username := 'user'; END IF;
  base_username := left(base_username, 24);
  candidate := base_username;
  WHILE EXISTS (SELECT 1 FROM public.profiles WHERE username=candidate) LOOP
    n := n + 1;
    candidate := left(base_username, greatest(1, 32-length(n::text)-1)) || '_' || n::text;
  END LOOP;

  INSERT INTO public.profiles(id,username,auth_email,display_name)
  VALUES(
    new.id,
    candidate,
    lower(coalesce(new.email,'')),
    coalesce(nullif(new.raw_user_meta_data->>'display_name',''), candidate)
  )
  ON CONFLICT (id) DO UPDATE SET
    auth_email=excluded.auth_email,
    display_name=coalesce(public.profiles.display_name,excluded.display_name),
    updated_at=now();

  INSERT INTO public.wallets(user_id,balance,available_balance,pending_balance)
  VALUES(new.id,0,0,0)
  ON CONFLICT(user_id) DO NOTHING;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Keep profile email synchronized after email changes.
CREATE OR REPLACE FUNCTION public.sync_user_email()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.profiles SET auth_email=lower(coalesce(new.email,'')), updated_at=now()
  WHERE id=new.id;
  RETURN new;
END;
$$;
DROP TRIGGER IF EXISTS on_auth_user_updated ON auth.users;
CREATE TRIGGER on_auth_user_updated
AFTER UPDATE OF email ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.sync_user_email();

-- ============================================================
-- PURCHASE MANAGEMENT
-- ============================================================
CREATE OR REPLACE FUNCTION public.delete_purchase(p_id uuid)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'LOGIN_REQUIRED'; END IF;
  DELETE FROM public.purchases
  WHERE id=p_id AND (buyer_id=auth.uid() OR public.is_current_user_admin());
  IF NOT FOUND THEN RAISE EXCEPTION 'PURCHASE_NOT_FOUND'; END IF;
  RETURN true;
END;
$$;

-- ============================================================
-- INDEXES
-- ============================================================

CREATE INDEX idx_profiles_username_lower ON public.profiles(lower(username));
CREATE INDEX idx_profiles_admin ON public.profiles(is_admin,role);
CREATE INDEX idx_orders_buyer ON public.orders(buyer_id,created_at DESC);
CREATE INDEX idx_orders_seller ON public.orders(seller_id,created_at DESC);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_payments_order ON public.payments(order_id);
CREATE INDEX idx_payments_user ON public.payments(user_id,created_at DESC);
CREATE INDEX idx_products_seller ON public.products(seller_id);
CREATE INDEX idx_products_status ON public.products(status);
CREATE INDEX idx_purchases_buyer ON public.purchases(buyer_id,created_at DESC);
CREATE INDEX idx_transactions_user ON public.transactions(user_id,created_at DESC);
CREATE INDEX idx_withdrawals_user ON public.withdrawals(user_id,created_at DESC);
CREATE INDEX idx_notifications_user ON public.notifications(user_id,is_read,created_at DESC);
CREATE INDEX idx_analytics_owner ON public.analytics_events(owner_id,created_at DESC);
CREATE INDEX idx_wallet_transactions_maturity ON public.wallet_transactions(user_id,available_at) WHERE status='pending';

-- ============================================================
-- HELPERS
-- ============================================================

CREATE OR REPLACE FUNCTION public.is_current_user_admin()
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER
SET search_path=public
AS $$
  SELECT EXISTS(
    SELECT 1 FROM public.profiles p
    WHERE p.id=auth.uid()
      AND p.is_banned=false
      AND (p.is_admin=true OR lower(p.role) IN ('admin','owner'))
  );
$$;

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at=now(); RETURN NEW; END $$;

DROP TRIGGER IF EXISTS trg_profiles_updated ON public.profiles;
CREATE TRIGGER trg_profiles_updated BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- ============================================================
-- USER HELPERS
-- ============================================================

CREATE OR REPLACE FUNCTION public.resolve_username_login(p_username text)
RETURNS TABLE(auth_email text,is_banned boolean)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public
AS $$
  SELECT p.auth_email,p.is_banned
  FROM public.profiles p
  WHERE lower(btrim(p.username))=lower(btrim(p_username))
  LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.check_username_available(p_username text)
RETURNS boolean
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public
AS $$
  SELECT NOT EXISTS(
    SELECT 1 FROM public.profiles
    WHERE lower(username)=lower(btrim(p_username))
  );
$$;

-- ============================================================
-- CHECKOUT
-- ============================================================

CREATE OR REPLACE FUNCTION public.create_checkout_order(p_type text,p_id text)
RETURNS TABLE(order_id uuid,amount numeric,item_title text,item_type text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
  uid uuid:=auth.uid();
  seller uuid;
  title text;
  price numeric;
  oid uuid;
  normalized text:=lower(btrim(coalesce(p_type,'')));
  pid uuid;
BEGIN
  IF uid IS NULL THEN RAISE EXCEPTION 'LOGIN_REQUIRED'; END IF;
  IF btrim(coalesce(p_id,''))='' THEN RAISE EXCEPTION 'PRODUCT_ID_REQUIRED'; END IF;

  BEGIN
    pid := p_id::uuid;
  EXCEPTION WHEN invalid_text_representation THEN
    RAISE EXCEPTION 'INVALID_PRODUCT_ID';
  END;

  IF normalized IN ('product','code') THEN
    SELECT p.seller_id,p.title,p.price INTO seller,title,price
    FROM public.products p WHERE p.id=pid;
  ELSIF normalized IN ('telegram_product','telegram-product') THEN
    SELECT p.owner_id,p.title,p.price INTO seller,title,price
    FROM public.telegram_products p WHERE p.id=pid;
  ELSIF normalized IN ('channel','telegram_channel','telegram-channel') THEN
    SELECT p.owner_id,p.name,p.price INTO seller,title,price
    FROM public.telegram_channels p WHERE p.id=pid;
  ELSIF normalized IN ('link','paste','pastelink','paste-link','paste_link') THEN
    SELECT p.user_id,p.title,0::numeric INTO seller,title,price
    FROM public.pastelinks p WHERE p.id=pid;
  ELSE
    RAISE EXCEPTION 'UNSUPPORTED_PRODUCT_TYPE';
  END IF;

  IF seller IS NULL THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
  IF seller=uid THEN RAISE EXCEPTION 'CANNOT_BUY_OWN_PRODUCT'; END IF;
  IF coalesce(price,0)<=0 THEN RAISE EXCEPTION 'PRODUCT_IS_FREE'; END IF;

  SELECT o.id INTO oid
  FROM public.orders o
  WHERE o.buyer_id=uid AND o.product_id=pid
    AND lower(coalesce(o.item_type,''))=normalized
    AND lower(coalesce(o.status,'')) IN ('pending','waiting','unpaid')
  ORDER BY o.created_at DESC LIMIT 1;

  IF oid IS NULL THEN
    INSERT INTO public.orders(buyer_id,seller_id,product_id,amount,status,item_type,item_id,item_title)
    VALUES(uid,seller,pid,price,'pending',normalized,p_id,title)
    RETURNING id INTO oid;
  END IF;

  RETURN QUERY SELECT oid,price,title,normalized;
END $$;

CREATE OR REPLACE FUNCTION public.create_account_plan_order(
  p_plan text,p_days integer,p_amount numeric
)
RETURNS TABLE(order_id uuid,amount numeric,item_title text,item_type text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
 uid uuid:=auth.uid(); oid uuid; expected numeric; title text;
 normalized text:=lower(btrim(coalesce(p_plan,'')));
BEGIN
 IF uid IS NULL THEN RAISE EXCEPTION 'LOGIN_REQUIRED'; END IF;

 IF normalized='premium' THEN expected:=250000; title:='PasTele Premium';
 ELSIF normalized='subscription_1' THEN expected:=15000; title:='Langganan PasTele 1 Hari';
 ELSIF normalized='subscription_3' THEN expected:=30000; title:='Langganan PasTele 3 Hari';
 ELSIF normalized='subscription_7' THEN expected:=50000; title:='Langganan PasTele 7 Hari';
 ELSE RAISE EXCEPTION 'INVALID_PLAN'; END IF;

 IF round(coalesce(p_amount,0),0)<>expected THEN RAISE EXCEPTION 'INVALID_PLAN_AMOUNT'; END IF;

 INSERT INTO public.orders(buyer_id,seller_id,product_id,amount,status,item_type,item_id,item_title)
 VALUES(uid,uid,NULL,expected,'pending','account_plan',normalized,title)
 RETURNING id INTO oid;

 RETURN QUERY SELECT oid,expected,title,'account_plan'::text;
END $$;

-- ============================================================
-- BAYAR.GG SETTLEMENT 70/30
-- ============================================================

CREATE OR REPLACE FUNCTION public.settle_bayargg_order(
 p_order_id uuid,p_invoice_id text,p_gateway_status text,
 p_final_amount numeric,p_gateway_payload jsonb DEFAULT '{}'::jsonb
)
RETURNS boolean
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
 o public.orders%ROWTYPE;
 seller_share numeric; platform_fee numeric;
 local_paid_at timestamp;
 v_available_at timestamptz;
 v_settlement_code text;
 v_balance_before numeric:=0;
BEGIN
 SELECT * INTO o FROM public.orders WHERE id=p_order_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'ORDER_NOT_FOUND'; END IF;
 IF lower(coalesce(o.status,'')) IN ('paid','success','completed','settled') THEN RETURN true; END IF;
 IF lower(coalesce(p_gateway_status,'')) NOT IN ('paid','settled','success') THEN RETURN false; END IF;
 IF round(coalesce(p_final_amount,0),0)<>round(coalesce(o.amount,0),0) THEN RAISE EXCEPTION 'AMOUNT_MISMATCH'; END IF;

 IF o.item_type='account_plan' THEN
   UPDATE public.orders SET status='paid',paid_at=coalesce(paid_at,now()),
     payment_reference=coalesce(p_invoice_id,payment_reference),
     gateway_payload=coalesce(p_gateway_payload,'{}'::jsonb) WHERE id=o.id;
   IF o.item_id='premium' THEN
     UPDATE public.profiles SET is_premium=true,updated_at=now() WHERE id=o.buyer_id;
   ELSIF o.item_id IN ('subscription_1','subscription_3','subscription_7') THEN
     UPDATE public.profiles SET subscription_until=greatest(coalesce(subscription_until,now()),now())+
       CASE o.item_id WHEN 'subscription_1' THEN interval '1 day' WHEN 'subscription_3' THEN interval '3 days'
       WHEN 'subscription_7' THEN interval '7 days' END,updated_at=now() WHERE id=o.buyer_id;
   END IF;
   INSERT INTO public.purchases(buyer_id,product_id,order_id,item_type,item_id,item_title,amount,status)
   SELECT o.buyer_id,NULL,o.id,o.item_type,o.item_id,o.item_title,o.amount,'completed'
   WHERE NOT EXISTS(SELECT 1 FROM public.purchases WHERE order_id=o.id);
   RETURN true;
 END IF;

 seller_share:=round(coalesce(o.amount,0)*0.70,2);
 platform_fee:=round(coalesce(o.amount,0)-seller_share,2);

 -- WIB/Asia-Jakarta settlement rule:
 -- before 21:00 WIB = H1 (next calendar day)
 -- 21:00 WIB or later = H2 (second calendar day)
 local_paid_at:=timezone('Asia/Jakarta',now());
 IF local_paid_at::time < time '21:00:00' THEN
   v_available_at:=timezone('Asia/Jakarta',date_trunc('day',local_paid_at)+interval '1 day');
   v_settlement_code:='H1';
 ELSE
   v_available_at:=timezone('Asia/Jakarta',date_trunc('day',local_paid_at)+interval '2 days');
   v_settlement_code:='H2';
 END IF;

 UPDATE public.orders SET status='paid',paid_at=coalesce(paid_at,now()),
   payment_reference=coalesce(p_invoice_id,payment_reference),
   gateway_payload=coalesce(p_gateway_payload,'{}'::jsonb) WHERE id=o.id;

 IF NOT EXISTS(SELECT 1 FROM public.purchases WHERE order_id=o.id) THEN
   SELECT coalesce(balance,0) INTO v_balance_before
   FROM public.wallets WHERE user_id=o.seller_id FOR UPDATE;

   -- 70% belongs to seller, but stays PENDING until H1/H2.
   INSERT INTO public.wallets(user_id,balance,available_balance,pending_balance)
   VALUES(o.seller_id,seller_share,0,seller_share)
   ON CONFLICT(user_id) DO UPDATE SET
     balance=public.wallets.balance+excluded.balance,
     pending_balance=public.wallets.pending_balance+excluded.pending_balance,
     updated_at=now();

   UPDATE public.profiles SET balance=balance+seller_share,updated_at=now() WHERE id=o.seller_id;

   INSERT INTO public.wallet_transactions(
     user_id,type,amount,balance_before,balance_after,reference,status,available_at,settlement_code
   ) VALUES(
     o.seller_id,'sale_earning',seller_share,v_balance_before,
     v_balance_before+seller_share,'bayargg-order:'||o.id::text,'pending',v_available_at,v_settlement_code
   );

   INSERT INTO public.transactions(user_id,amount,fee,net_amount,type,status,reference,description)
   VALUES(o.seller_id,seller_share,platform_fee,seller_share,'sale_earning','pending',
          'bayargg-order:'||o.id::text,'Marketplace sale 70/30 - '||v_settlement_code)
   ON CONFLICT(user_id,reference) DO NOTHING;

   IF lower(coalesce(o.item_type,'')) IN ('product','code') THEN
     UPDATE public.products SET sales_count=sales_count+1,updated_at=now() WHERE id=o.product_id;
   ELSIF lower(coalesce(o.item_type,''))='telegram_product' THEN
     UPDATE public.telegram_products SET sales_count=sales_count+1,updated_at=now() WHERE id=o.product_id;
   ELSIF lower(coalesce(o.item_type,'')) IN ('channel','telegram_channel','telegram-channel','group','telegram_group','telegram-group') THEN
     UPDATE public.telegram_channels SET sales_count=sales_count+1,updated_at=now() WHERE id=o.product_id;
   END IF;

   INSERT INTO public.purchases(buyer_id,product_id,order_id,item_type,item_id,item_title,amount,status)
   VALUES(o.buyer_id,o.product_id,o.id,o.item_type,o.item_id,o.item_title,o.amount,'completed');
 END IF;
 RETURN true;
END $$;

-- ============================================================
-- MARKETPLACE
-- ============================================================

CREATE OR REPLACE FUNCTION public.buy_market_item(p_type text,p_id uuid)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
 r record; result jsonb;
BEGIN
 SELECT * INTO r FROM public.create_checkout_order(p_type,p_id::text);
 result:=jsonb_build_object(
   'order_id',r.order_id,'amount',r.amount,
   'item_title',r.item_title,'item_type',r.item_type
 );
 RETURN result;
END $$;

CREATE OR REPLACE FUNCTION public.get_market_item_detail(p_type text,p_id uuid)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE r record;
BEGIN
 IF lower(p_type) IN ('product','code') THEN
   SELECT p.*,pr.username creator_username,pr.display_name creator_name
   INTO r FROM public.products p
   LEFT JOIN public.profiles pr ON pr.id=coalesce(p.creator_id,p.seller_id)
   WHERE p.id=p_id;
 ELSIF lower(p_type)='telegram_product' THEN
   SELECT p.*,pr.username creator_username,pr.display_name creator_name
   INTO r FROM public.telegram_products p
   LEFT JOIN public.profiles pr ON pr.id=p.owner_id
   WHERE p.id=p_id;
 ELSE
   RAISE EXCEPTION 'UNSUPPORTED_PRODUCT_TYPE';
 END IF;

 IF r IS NULL THEN RETURN jsonb_build_object('found',false); END IF;
 RETURN to_jsonb(r)||jsonb_build_object('found',true);
END $$;

-- ============================================================
-- WALLET / WITHDRAWAL
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_pending_balance_detail()
RETURNS TABLE(
 id uuid,amount numeric,created_at timestamptz,
 available_at timestamptz,hold_label text
)
LANGUAGE sql SECURITY DEFINER SET search_path=public
AS $$
 SELECT wt.id,wt.amount,wt.created_at,wt.available_at,
        CASE wt.settlement_code WHEN 'H2' THEN 'Settlement H2' ELSE 'Settlement H1' END
 FROM public.wallet_transactions wt
 WHERE wt.user_id=auth.uid()
   AND wt.status='pending'
 ORDER BY wt.available_at ASC,wt.created_at DESC;
$$;

CREATE OR REPLACE FUNCTION public.release_matured_wallet()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE moved numeric:=0; uid uuid:=auth.uid();
BEGIN
 IF uid IS NULL THEN RAISE EXCEPTION 'LOGIN_REQUIRED'; END IF;

 SELECT coalesce(sum(amount),0) INTO moved
 FROM public.wallet_transactions
 WHERE user_id=uid AND status='pending'
   AND available_at IS NOT NULL AND available_at<=now();

 UPDATE public.wallet_transactions
 SET status='completed'
 WHERE user_id=uid AND status='pending'
   AND available_at IS NOT NULL AND available_at<=now();

 IF moved>0 THEN
   UPDATE public.wallets
   SET pending_balance=greatest(0,pending_balance-moved),
       available_balance=available_balance+moved,updated_at=now()
   WHERE user_id=uid;

   UPDATE public.transactions t
   SET status='completed'
   WHERE t.user_id=uid AND t.type='sale_earning' AND t.status='pending'
     AND EXISTS (
       SELECT 1 FROM public.wallet_transactions wt
       WHERE wt.user_id=uid AND wt.reference=t.reference
         AND wt.status='completed' AND wt.available_at<=now()
     );
 END IF;

 RETURN jsonb_build_object('released',moved);
END $$;

CREATE OR REPLACE FUNCTION public.release_all_matured_wallets()
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
 r record; moved_total numeric:=0; moved_users integer:=0;
BEGIN
 FOR r IN
   SELECT wt.user_id,coalesce(sum(wt.amount),0) AS amount
   FROM public.wallet_transactions wt
   WHERE wt.status='pending'
     AND wt.available_at IS NOT NULL
     AND wt.available_at<=now()
     AND wt.user_id IS NOT NULL
   GROUP BY wt.user_id
 LOOP
   UPDATE public.wallet_transactions
   SET status='completed'
   WHERE user_id=r.user_id AND status='pending'
     AND available_at IS NOT NULL AND available_at<=now();

   UPDATE public.wallets
   SET pending_balance=greatest(0,pending_balance-r.amount),
       available_balance=available_balance+r.amount,updated_at=now()
   WHERE user_id=r.user_id;

   UPDATE public.transactions t
   SET status='completed'
   WHERE t.user_id=r.user_id AND t.type='sale_earning' AND t.status='pending'
     AND EXISTS (
       SELECT 1 FROM public.wallet_transactions wt
       WHERE wt.user_id=r.user_id AND wt.reference=t.reference
         AND wt.status='completed' AND wt.available_at<=now()
     );

   moved_total:=moved_total+r.amount;
   moved_users:=moved_users+1;
 END LOOP;

 RETURN jsonb_build_object('released',moved_total,'users',moved_users);
END $$;

CREATE OR REPLACE FUNCTION public.request_withdrawal_v2(
 p_amount numeric,p_mode text,p_method text,p_account_name text,p_account_number text
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE
 uid uuid:=auth.uid(); wid uuid; available numeric:=0;
 fee numeric:=0; net_amount numeric:=0; total_debit numeric:=0;
 mode_normalized text:=lower(btrim(coalesce(p_mode,'')));
BEGIN
 IF uid IS NULL THEN RAISE EXCEPTION 'LOGIN_REQUIRED'; END IF;
 IF p_amount IS NULL OR p_amount<=0 THEN RAISE EXCEPTION 'INVALID_WITHDRAWAL_AMOUNT'; END IF;

 -- Manual WD: fee Rp7.000. Instant WD: fee Rp15.000.
 IF mode_normalized='instant' THEN
   IF p_amount<50000 THEN RAISE EXCEPTION 'MINIMUM_INSTANT_WITHDRAWAL_50000'; END IF;
   IF p_amount>250000 THEN RAISE EXCEPTION 'MAXIMUM_INSTANT_WITHDRAWAL_250000'; END IF;
   fee:=15000;
 ELSIF mode_normalized='manual' THEN
   IF p_amount<10000 THEN RAISE EXCEPTION 'MINIMUM_MANUAL_WITHDRAWAL_10000'; END IF;
   fee:=7000;
 ELSE
   RAISE EXCEPTION 'INVALID_WITHDRAWAL_MODE';
 END IF;

 net_amount:=greatest(0,p_amount-fee);
 total_debit:=p_amount+fee;

 SELECT available_balance INTO available
 FROM public.wallets WHERE user_id=uid FOR UPDATE;
 IF coalesce(available,0)<total_debit THEN RAISE EXCEPTION 'INSUFFICIENT_BALANCE'; END IF;

 UPDATE public.wallets
 SET available_balance=available_balance-total_debit,
     balance=balance-total_debit,
     updated_at=now()
 WHERE user_id=uid;

 UPDATE public.profiles
 SET balance=balance-total_debit,updated_at=now()
 WHERE id=uid;

 INSERT INTO public.withdrawals(
   user_id,amount,fee,net_amount,mode,method,account_name,account_number,status
 ) VALUES(uid,p_amount,fee,net_amount,mode_normalized,p_method,p_account_name,p_account_number,'pending')
 RETURNING id INTO wid;

 INSERT INTO public.transactions(
   user_id,amount,fee,net_amount,type,status,reference,description
 ) VALUES(
   uid,fee,fee,fee,'withdrawal_fee','completed',
   'withdrawal-fee:'||wid::text,
   CASE WHEN mode_normalized='instant' THEN 'WD Instant fee Rp15.000' ELSE 'WD Manual fee Rp7.000' END
 );

 RETURN jsonb_build_object(
   'id',wid,'status','pending','amount',p_amount,'fee',fee,
   'net_amount',net_amount,'total_debit',total_debit,'mode',mode_normalized
 );
END $$;

-- ============================================================
-- ANALYTICS
-- ============================================================

CREATE OR REPLACE FUNCTION public.increment_paste_view(p_id uuid)
RETURNS bigint
LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE v bigint;
BEGIN
 UPDATE public.pastelinks SET views=views+1 WHERE id=p_id RETURNING views INTO v;
 RETURN coalesce(v,0);
END $$;

CREATE OR REPLACE FUNCTION public.record_content_view(
 p_target_id uuid,p_target_type text,p_owner uuid DEFAULT NULL
)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
BEGIN
 INSERT INTO public.analytics_events(owner_id,actor_id,event_type,target_type,target_id)
 VALUES(coalesce(p_owner,auth.uid()),auth.uid(),'view',p_target_type,p_target_id);
 RETURN true;
END $$;

CREATE OR REPLACE FUNCTION public.toggle_content_like(
 p_target_id uuid,p_target_type text,p_owner uuid DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE liked boolean;
BEGIN
 IF auth.uid() IS NULL THEN RAISE EXCEPTION 'LOGIN_REQUIRED'; END IF;
 SELECT EXISTS(SELECT 1 FROM public.content_likes
   WHERE actor_id=auth.uid() AND target_id=p_target_id AND target_type=p_target_type) INTO liked;
 IF liked THEN
   DELETE FROM public.content_likes
   WHERE actor_id=auth.uid() AND target_id=p_target_id AND target_type=p_target_type;
   RETURN jsonb_build_object('liked',false);
 ELSE
   INSERT INTO public.content_likes(content_owner_id,actor_id,target_id,target_type)
   VALUES(coalesce(p_owner,auth.uid()),auth.uid(),p_target_id,p_target_type);
   RETURN jsonb_build_object('liked',true);
 END IF;
END $$;

CREATE OR REPLACE FUNCTION public.track_analytics(
 p_event_type text DEFAULT NULL,p_target_type text DEFAULT NULL,p_target_id uuid DEFAULT NULL,p_owner uuid DEFAULT NULL
)
RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
BEGIN
 INSERT INTO public.analytics_events(owner_id,actor_id,event_type,target_type,target_id)
 VALUES(coalesce(p_owner,auth.uid()),auth.uid(),coalesce(p_event_type,''),p_target_type,p_target_id);
 RETURN true;
END $$;

-- ============================================================
-- PUBLIC SETTINGS / STATS
-- ============================================================

CREATE OR REPLACE FUNCTION public.get_public_site_settings()
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public
AS $$
 SELECT coalesce(settings,'{}'::jsonb)
 FROM public.site_settings WHERE id=1;
$$;

CREATE OR REPLACE FUNCTION public.get_public_workspace_stats()
RETURNS jsonb
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public
AS $$
 SELECT jsonb_build_object(
   'users',(SELECT count(*) FROM public.profiles WHERE is_banned=false),
   'products',(SELECT count(*) FROM public.products WHERE status IN ('published','active')),
   'orders',(SELECT count(*) FROM public.orders WHERE status IN ('paid','success','completed')),
   'sales',(SELECT coalesce(sum(amount),0) FROM public.orders WHERE status IN ('paid','success','completed'))
 );
$$;

-- ============================================================
-- ADMIN RPC
-- ============================================================

CREATE OR REPLACE FUNCTION public.admin_stats()
RETURNS SETOF jsonb
LANGUAGE sql SECURITY DEFINER SET search_path=public
AS $$
 SELECT jsonb_build_object(
   'total_users',(SELECT count(*) FROM public.profiles),
   'active_users',(SELECT count(*) FROM public.profiles WHERE is_banned=false),
   'banned_users',(SELECT count(*) FROM public.profiles WHERE is_banned=true),
   'total_products',(SELECT count(*) FROM public.products),
   'published_products',(SELECT count(*) FROM public.products WHERE status IN ('published','active')),
   'total_orders',(SELECT count(*) FROM public.orders),
   'paid_orders',(SELECT count(*) FROM public.orders WHERE status IN ('paid','success','completed')),
   'pending_orders',(SELECT count(*) FROM public.orders WHERE status IN ('pending','waiting','unpaid')),
   'total_payments',(SELECT count(*) FROM public.payments),
   'total_withdrawals',(SELECT count(*) FROM public.withdrawals),
   'pending_withdrawals',(SELECT count(*) FROM public.withdrawals WHERE status='pending'),
   'gross_sales',(SELECT coalesce(sum(amount),0) FROM public.orders WHERE status IN ('paid','success','completed')),
   'seller_earnings',(SELECT coalesce(sum(net_amount),0) FROM public.transactions WHERE type='sale_earning'),
   'platform_fee',(SELECT coalesce(sum(fee),0) FROM public.transactions WHERE type='sale_earning'),
   'users',(SELECT count(*) FROM public.profiles),
   'products',(SELECT count(*) FROM public.products),
   'orders',(SELECT count(*) FROM public.orders),
   'sales',(SELECT coalesce(sum(amount),0) FROM public.orders WHERE status IN ('paid','success','completed')),
   'revenue',(SELECT coalesce(sum(fee),0) FROM public.transactions WHERE type='sale_earning'),
   'pastes',(SELECT count(*) FROM public.pastes),
   'views',(SELECT coalesce(sum(views),0) FROM public.products),
   'banned',(SELECT count(*) FROM public.profiles WHERE is_banned=true),
   'pending',(SELECT count(*) FROM public.orders WHERE status IN ('pending','waiting','unpaid')),
   'withdrawal_fee_revenue',(SELECT coalesce(sum(amount),0) FROM public.transactions WHERE type='withdrawal_fee'),
   'total_platform_revenue',(SELECT coalesce(sum(fee),0) FROM public.transactions WHERE type='sale_earning') + (SELECT coalesce(sum(amount),0) FROM public.transactions WHERE type='withdrawal_fee')
 )
 WHERE public.is_current_user_admin();
$$;

CREATE OR REPLACE FUNCTION public.admin_site_stats()
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public
AS $$ SELECT coalesce((SELECT row_to_json(s)::jsonb FROM public.site_stats s WHERE id=1 AND public.is_current_user_admin()),'{}'::jsonb); $$;

CREATE OR REPLACE FUNCTION public.admin_users(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(p) FROM public.profiles p
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_products(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(p) FROM public.products p
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_orders(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(o) FROM public.orders o
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_payments(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(p) FROM public.payments p
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_transactions(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(t) FROM public.transactions t
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_withdrawals(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(w) FROM public.withdrawals w
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_pastes(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(p) FROM public.pastes p
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_bots(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(b) FROM public.approved_bots b
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_logs(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(l) FROM public.admin_logs l
 WHERE public.is_current_user_admin()
 ORDER BY created_at DESC LIMIT greatest(1,least(p_limit,200)) OFFSET greatest(0,p_offset);
$$;

CREATE OR REPLACE FUNCTION public.admin_content(p_limit integer DEFAULT 50,p_offset integer DEFAULT 0)
RETURNS SETOF jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT to_jsonb(x) FROM (
   SELECT p.id,p.title,p.slug,p.price,p.status,p.description,p.views,p.sales_count,p.creator_id,p.seller_id,
          NULL::uuid AS owner_id,NULL::uuid AS user_id,'products'::text AS source,p.type,p.thumbnail_url,p.created_at,p.updated_at
   FROM public.products p
   UNION ALL
   SELECT pl.id,pl.title,pl.slug,0::numeric,CASE WHEN pl.visibility='public' THEN 'published' ELSE pl.visibility END,
          pl.description,pl.views,0::bigint,NULL::uuid,NULL::uuid,NULL::uuid,pl.user_id,
          'pastelinks'::text,'link'::text,NULL::text,pl.created_at,pl.updated_at
   FROM public.pastelinks pl
   UNION ALL
   SELECT tp.id,tp.title,tp.slug,tp.price,tp.status,tp.description,tp.views,tp.sales_count,NULL::uuid,NULL::uuid,
          tp.owner_id,NULL::uuid,'telegram_products'::text,'code'::text,tp.thumbnail_url,tp.created_at,tp.updated_at
   FROM public.telegram_products tp
   UNION ALL
   SELECT tc.id,tc.name AS title,NULL::text,tc.price,tc.status,tc.description,tc.views,tc.sales_count,NULL::uuid,NULL::uuid,
          tc.owner_id,NULL::uuid,'telegram_channels'::text,'channel'::text,NULL::text,tc.created_at,tc.updated_at
   FROM public.telegram_channels tc
 ) x
 WHERE public.is_current_user_admin()
 ORDER BY x.created_at DESC
 LIMIT greatest(1,least(coalesce(p_limit,50),500))
 OFFSET greatest(coalesce(p_offset,0),0);
$$;

CREATE OR REPLACE FUNCTION public.admin_payment_methods(p_user uuid)
RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=public AS $$
 SELECT coalesce(jsonb_agg(to_jsonb(m) ORDER BY m.created_at DESC),'[]'::jsonb)
 FROM public.payment_methods m WHERE m.user_id=p_user AND public.is_current_user_admin();
$$;

CREATE OR REPLACE FUNCTION public.admin_set_user(p_user uuid,p_banned boolean,p_admin boolean)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r public.profiles;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 UPDATE public.profiles
 SET is_banned=p_banned,is_admin=p_admin,
     role=CASE WHEN p_admin THEN 'admin' ELSE 'user' END,
     updated_at=now()
 WHERE id=p_user
 RETURNING * INTO r;

 IF r.id IS NULL THEN RAISE EXCEPTION 'USER_NOT_FOUND'; END IF;

 INSERT INTO public.admin_logs(admin_id,action,target_id,details)
 VALUES(auth.uid(),'admin_set_user',p_user,
        jsonb_build_object('banned',p_banned,'admin',p_admin));

 RETURN to_jsonb(r);
END $$;

CREATE OR REPLACE FUNCTION public.admin_adjust_balance(
 p_user uuid,p_amount numeric,p_reason text
)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;

 INSERT INTO public.wallets(user_id,balance,available_balance,pending_balance)
 VALUES(p_user,p_amount,p_amount,0)
 ON CONFLICT(user_id) DO UPDATE SET
   balance=public.wallets.balance+p_amount,
   available_balance=public.wallets.available_balance+p_amount,
   updated_at=now();

 UPDATE public.profiles
 SET balance=balance+p_amount,updated_at=now()
 WHERE id=p_user;

 INSERT INTO public.transactions(user_id,amount,fee,net_amount,type,status,reference,description)
 VALUES(p_user,p_amount,0,p_amount,'admin_adjustment','completed',
        'admin-adjustment:'||gen_random_uuid()::text,coalesce(p_reason,'Admin balance adjustment'));
END $$;

CREATE OR REPLACE FUNCTION public.admin_update_product(p_id uuid,p_status text,p_price numeric)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r public.products;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 UPDATE public.products SET status=p_status,price=p_price,updated_at=now()
 WHERE id=p_id RETURNING * INTO r;
 IF r.id IS NULL THEN RAISE EXCEPTION 'PRODUCT_NOT_FOUND'; END IF;
 RETURN to_jsonb(r);
END $$;

CREATE OR REPLACE FUNCTION public.admin_delete_product(p_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 DELETE FROM public.products WHERE id=p_id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_delete_paste(p_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 DELETE FROM public.pastes WHERE id=p_id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_delete_bot(p_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 DELETE FROM public.approved_bots WHERE id=p_id;
END $$;

CREATE OR REPLACE FUNCTION public.admin_set_bot_active(p_bot_id uuid,p_active boolean)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r public.approved_bots;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 UPDATE public.approved_bots SET is_active=p_active,updated_at=now()
 WHERE id=p_bot_id RETURNING * INTO r;
 RETURN to_jsonb(r);
END $$;

CREATE OR REPLACE FUNCTION public.admin_upsert_bot(
 p_username text,p_bot_id bigint,p_display_name text
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r public.approved_bots;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 INSERT INTO public.approved_bots(bot_username,bot_id,bot_name,is_active)
 VALUES(lower(btrim(p_username)),p_bot_id,p_display_name,true)
 ON CONFLICT(bot_username) DO UPDATE SET
   bot_id=excluded.bot_id,
   bot_name=excluded.bot_name,
   is_active=true,
   updated_at=now()
 RETURNING * INTO r;
 RETURN to_jsonb(r);
END $$;

CREATE OR REPLACE FUNCTION public.admin_mark_order_paid(
 p_order_id uuid,p_payment_reference text
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE o public.orders;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 UPDATE public.orders
 SET status='paid',paid_at=coalesce(paid_at,now()),
     payment_reference=coalesce(p_payment_reference,payment_reference)
 WHERE id=p_order_id RETURNING * INTO o;

 IF o.id IS NULL THEN RAISE EXCEPTION 'ORDER_NOT_FOUND'; END IF;
 RETURN to_jsonb(o);
END $$;

CREATE OR REPLACE FUNCTION public.admin_cancel_order(p_order_id uuid)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE o public.orders;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 UPDATE public.orders SET status='cancelled'
 WHERE id=p_order_id RETURNING * INTO o;
 IF o.id IS NULL THEN RAISE EXCEPTION 'ORDER_NOT_FOUND'; END IF;
 RETURN to_jsonb(o);
END $$;

CREATE OR REPLACE FUNCTION public.admin_process_withdrawal(
 p_id uuid,p_status text,p_note text
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public
AS $$
DECLARE w public.withdrawals%ROWTYPE; old_status text; refund numeric:=0;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 IF lower(coalesce(p_status,'')) NOT IN ('pending','approved','rejected','completed','cancelled')
 THEN RAISE EXCEPTION 'INVALID_WITHDRAWAL_STATUS'; END IF;

 SELECT * INTO w FROM public.withdrawals WHERE id=p_id FOR UPDATE;
 IF NOT FOUND THEN RAISE EXCEPTION 'WITHDRAWAL_NOT_FOUND'; END IF;
 old_status:=lower(coalesce(w.status,''));

 UPDATE public.withdrawals SET status=lower(p_status),note=p_note,
   processed_at=CASE WHEN lower(p_status) IN ('approved','rejected','completed','cancelled') THEN now() ELSE processed_at END
 WHERE id=p_id RETURNING * INTO w;

 IF lower(p_status) IN ('rejected','cancelled') AND old_status NOT IN ('rejected','cancelled') THEN
   refund:=coalesce(w.amount,0)+coalesce(w.fee,0);
   UPDATE public.wallets SET balance=balance+refund,available_balance=available_balance+refund,updated_at=now()
   WHERE user_id=w.user_id;
   UPDATE public.profiles SET balance=balance+refund,updated_at=now() WHERE id=w.user_id;

   INSERT INTO public.transactions(
     user_id,amount,fee,net_amount,type,status,reference,description
   ) VALUES(
     w.user_id,-coalesce(w.fee,0),-coalesce(w.fee,0),-coalesce(w.fee,0),
     'withdrawal_fee_refund','completed','withdrawal-fee-refund:'||w.id::text,
     'Refund WD fee'
   )
   ON CONFLICT(user_id,reference) DO NOTHING;
 END IF;
 RETURN to_jsonb(w);
END $$;

CREATE OR REPLACE FUNCTION public.admin_publish_announcement(
 p_title text,p_body text,p_image_url text
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r public.announcements;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 INSERT INTO public.announcements(title,body,image_url,published,published_at)
 VALUES(p_title,p_body,p_image_url,true,now())
 RETURNING * INTO r;
 RETURN to_jsonb(r);
END $$;

CREATE OR REPLACE FUNCTION public.admin_save_socials(p_socials jsonb)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 UPDATE public.site_settings
 SET settings=coalesce(settings,'{}'::jsonb)||jsonb_build_object('socials',p_socials),
     updated_at=now()
 WHERE id=1;
 RETURN public.get_public_site_settings();
END $$;

CREATE OR REPLACE FUNCTION public.admin_update_content(
 p_id uuid,p_status text DEFAULT NULL,p_title text DEFAULT NULL,p_description text DEFAULT NULL,
 p_source text DEFAULT 'products',p_slug text DEFAULT NULL,p_price numeric DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE r jsonb;
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 CASE lower(coalesce(p_source,'products'))
  WHEN 'products' THEN
   UPDATE public.products SET status=coalesce(p_status,status),title=coalesce(p_title,title),
     slug=coalesce(nullif(p_slug,''),slug),price=coalesce(p_price,price),
     description=coalesce(p_description,description),updated_at=now()
   WHERE id=p_id RETURNING to_jsonb(products.*) INTO r;
  WHEN 'pastelinks' THEN
   UPDATE public.pastelinks SET visibility=CASE WHEN p_status='published' THEN 'public'
     WHEN p_status IS NULL THEN visibility ELSE p_status END,
     title=coalesce(p_title,title),description=coalesce(p_description,description),updated_at=now()
   WHERE id=p_id RETURNING to_jsonb(pastelinks.*) INTO r;
  WHEN 'telegram_products' THEN
   UPDATE public.telegram_products SET status=coalesce(p_status,status),title=coalesce(p_title,title),
     price=coalesce(p_price,price),description=coalesce(p_description,description),updated_at=now()
   WHERE id=p_id RETURNING to_jsonb(telegram_products.*) INTO r;
  WHEN 'telegram_channels' THEN
   UPDATE public.telegram_channels SET status=coalesce(p_status,status),name=coalesce(p_title,name),
     price=coalesce(p_price,price),description=coalesce(p_description,description),updated_at=now()
   WHERE id=p_id RETURNING to_jsonb(telegram_channels.*) INTO r;
  ELSE RAISE EXCEPTION 'UNSUPPORTED_CONTENT_SOURCE';
 END CASE;
 IF r IS NULL THEN RAISE EXCEPTION 'CONTENT_NOT_FOUND'; END IF;
 RETURN r;
END $$;

CREATE OR REPLACE FUNCTION public.admin_delete_content(p_id uuid,p_source text DEFAULT 'products')
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
BEGIN
 IF NOT public.is_current_user_admin() THEN RAISE EXCEPTION 'ADMIN_REQUIRED'; END IF;
 CASE lower(coalesce(p_source,'products'))
  WHEN 'products' THEN DELETE FROM public.products WHERE id=p_id;
  WHEN 'pastelinks' THEN DELETE FROM public.pastelinks WHERE id=p_id;
  WHEN 'telegram_products' THEN DELETE FROM public.telegram_products WHERE id=p_id;
  WHEN 'telegram_channels' THEN DELETE FROM public.telegram_channels WHERE id=p_id;
  ELSE RAISE EXCEPTION 'UNSUPPORTED_CONTENT_SOURCE';
 END CASE;
END $$;

-- ============================================================
-- RLS
-- ============================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_methods ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pastelinks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pastes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;

CREATE POLICY profiles_select_own_or_admin ON public.profiles
FOR SELECT TO authenticated
USING(id=auth.uid() OR public.is_current_user_admin());
CREATE POLICY profiles_public_read ON public.profiles
FOR SELECT TO anon
USING(is_banned=false);

CREATE POLICY profiles_update_own_or_admin ON public.profiles
FOR UPDATE TO authenticated
USING(id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY products_public_read ON public.products
FOR SELECT TO anon,authenticated
USING(status IN ('published','active') OR seller_id=auth.uid() OR creator_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY products_owner_write ON public.products
FOR ALL TO authenticated
USING(seller_id=auth.uid() OR creator_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(seller_id=auth.uid() OR creator_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY orders_buyer_seller_admin ON public.orders
FOR SELECT TO authenticated
USING(buyer_id=auth.uid() OR seller_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY payments_owner_admin ON public.payments
FOR SELECT TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY payment_methods_owner ON public.payment_methods
FOR ALL TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY notifications_owner ON public.notifications
FOR ALL TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY pastelinks_owner_or_public ON public.pastelinks
FOR SELECT TO anon,authenticated
USING(visibility='public' OR user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY pastelinks_owner_write ON public.pastelinks
FOR ALL TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY pastes_owner_or_public ON public.pastes
FOR SELECT TO anon,authenticated
USING(visibility='public' OR owner_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY pastes_owner_write ON public.pastes
FOR ALL TO authenticated
USING(owner_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(owner_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY purchases_owner_admin ON public.purchases
FOR SELECT TO authenticated
USING(buyer_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY withdrawals_owner_admin ON public.withdrawals
FOR SELECT TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY transactions_owner_admin ON public.transactions
FOR SELECT TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY wallets_owner_admin ON public.wallets
FOR SELECT TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin());


-- Additional RLS for tables used directly by the web app.
ALTER TABLE public.telegram_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.telegram_channels ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.creator_followers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_likes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_views ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.analytics_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.code_access_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.approved_bots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bot_integrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.content_comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_access ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.admin_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_stats ENABLE ROW LEVEL SECURITY;

CREATE POLICY telegram_products_public_read ON public.telegram_products
FOR SELECT TO anon,authenticated
USING(status IN ('published','active') OR owner_id=auth.uid() OR public.is_current_user_admin());
CREATE POLICY telegram_products_owner_write ON public.telegram_products
FOR ALL TO authenticated
USING(owner_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(owner_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY telegram_channels_public_read ON public.telegram_channels
FOR SELECT TO anon,authenticated
USING(status IN ('published','active') OR owner_id=auth.uid() OR public.is_current_user_admin());
CREATE POLICY telegram_channels_owner_write ON public.telegram_channels
FOR ALL TO authenticated
USING(owner_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(owner_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY followers_read ON public.creator_followers
FOR SELECT TO authenticated USING(creator_id=auth.uid() OR follower_id=auth.uid() OR public.is_current_user_admin());
CREATE POLICY followers_write ON public.creator_followers
FOR ALL TO authenticated
USING(follower_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(follower_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY likes_read ON public.content_likes
FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY likes_write ON public.content_likes
FOR ALL TO authenticated
USING(actor_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(actor_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY product_views_public_insert ON public.product_views
FOR INSERT TO anon,authenticated WITH CHECK(true);
CREATE POLICY product_views_admin_read ON public.product_views
FOR SELECT TO authenticated USING(public.is_current_user_admin());

CREATE POLICY announcements_public_read ON public.announcements
FOR SELECT TO anon,authenticated USING(published=true OR public.is_current_user_admin());
CREATE POLICY announcements_admin_write ON public.announcements
FOR ALL TO authenticated
USING(public.is_current_user_admin()) WITH CHECK(public.is_current_user_admin());

CREATE POLICY analytics_owner_write ON public.analytics_events
FOR INSERT TO authenticated WITH CHECK(owner_id=auth.uid() OR actor_id=auth.uid() OR public.is_current_user_admin());
CREATE POLICY analytics_owner_read ON public.analytics_events
FOR SELECT TO authenticated USING(owner_id=auth.uid() OR actor_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY usage_owner ON public.code_access_usage
FOR ALL TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY login_history_owner ON public.login_history
FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY approved_bots_public_read ON public.approved_bots
FOR SELECT TO anon,authenticated USING(is_active=true OR public.is_current_user_admin());
CREATE POLICY approved_bots_admin_write ON public.approved_bots
FOR ALL TO authenticated USING(public.is_current_user_admin()) WITH CHECK(public.is_current_user_admin());

CREATE POLICY bot_integrations_owner ON public.bot_integrations
FOR ALL TO authenticated
USING(owner_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(owner_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY payment_settings_public_read ON public.payment_settings
FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY payment_settings_admin_write ON public.payment_settings
FOR ALL TO authenticated USING(public.is_current_user_admin()) WITH CHECK(public.is_current_user_admin());

CREATE POLICY comments_public_read ON public.content_comments
FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY comments_owner_write ON public.content_comments
FOR ALL TO authenticated
USING(user_id=auth.uid() OR public.is_current_user_admin())
WITH CHECK(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY access_buyer_owner ON public.product_access
FOR SELECT TO authenticated USING(buyer_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY wallet_transactions_owner ON public.wallet_transactions
FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.is_current_user_admin());

CREATE POLICY admins_admin_only ON public.admins
FOR ALL TO authenticated USING(public.is_current_user_admin()) WITH CHECK(public.is_current_user_admin());
CREATE POLICY admin_logs_admin_only ON public.admin_logs
FOR SELECT TO authenticated USING(public.is_current_user_admin());
CREATE POLICY site_settings_public_read ON public.site_settings
FOR SELECT TO anon,authenticated USING(true);
CREATE POLICY site_settings_admin_write ON public.site_settings
FOR ALL TO authenticated USING(public.is_current_user_admin()) WITH CHECK(public.is_current_user_admin());
CREATE POLICY site_stats_public_read ON public.site_stats
FOR SELECT TO anon,authenticated USING(true);

-- ============================================================
-- GRANTS
-- ============================================================

GRANT USAGE ON SCHEMA public TO anon,authenticated,service_role;
GRANT SELECT ON public.profile_public,public.marketplace_public TO anon,authenticated;
GRANT SELECT (id,username,display_name,avatar_url,country,created_at)
ON public.profiles TO anon;
GRANT SELECT ON public.products,public.pastelinks,public.pastes,public.announcements TO anon,authenticated;

GRANT SELECT,INSERT,UPDATE,DELETE ON
 public.products,public.telegram_products,public.telegram_channels,
 public.pastelinks,public.pastes,public.payment_methods,public.notifications,
 public.creator_followers,public.content_likes,public.content_comments
TO authenticated;
GRANT SELECT,UPDATE ON public.profiles TO authenticated;
GRANT SELECT ON public.announcements,public.payment_settings,public.site_settings,public.site_stats TO anon,authenticated;
GRANT INSERT ON public.product_views TO anon,authenticated;
GRANT SELECT,INSERT ON public.analytics_events TO authenticated;
GRANT SELECT ON public.wallets,public.transactions,public.wallet_transactions,public.withdrawals,public.purchases,public.product_access TO authenticated;

GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

REVOKE ALL ON FUNCTION public.release_all_matured_wallets() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.release_all_matured_wallets() TO service_role;

-- ============================================================
-- OPTIONAL AUTOMATIC SETTLEMENT RELEASE (PG_CRON)
-- Runs hourly. If pg_cron is unavailable, the SQL continues.
-- The settlement timestamp itself is already stored per sale.
-- ============================================================
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_available_extensions WHERE name='pg_cron'
  ) THEN
    BEGIN
      CREATE EXTENSION IF NOT EXISTS pg_cron WITH SCHEMA extensions;
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'pg_cron could not be enabled: %', SQLERRM;
    END;

    IF EXISTS (
      SELECT 1 FROM pg_proc p
      JOIN pg_namespace n ON n.oid=p.pronamespace
      WHERE n.nspname='cron' AND p.proname='schedule'
    ) THEN
      BEGIN
        PERFORM cron.unschedule(jobid)
        FROM cron.job
        WHERE jobname='pastele-release-matured-wallets';
      EXCEPTION WHEN OTHERS THEN
        NULL;
      END;

      PERFORM cron.schedule(
        'pastele-release-matured-wallets',
        '0 * * * *',
        $cron$SELECT public.release_all_matured_wallets();$cron$
      );
    END IF;
  END IF;
END $$;


-- Service role can execute settlement.
REVOKE ALL ON FUNCTION public.settle_bayargg_order(uuid,text,text,numeric,jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.settle_bayargg_order(uuid,text,text,numeric,jsonb) TO service_role;

-- ============================================================
-- RECREATE ADMIM ADMIN FLAG
-- Existing auth user is preserved. If profile exists, promote it.
-- ============================================================

UPDATE public.profiles
SET role='admin',is_admin=true,is_banned=false,updated_at=now()
WHERE lower(btrim(username))='admim';

-- ============================================================
-- STATISTICS REFRESH
-- ============================================================

UPDATE public.site_stats
SET total_users=(SELECT count(*) FROM public.profiles),
    total_products=(SELECT count(*) FROM public.products),
    total_orders=(SELECT count(*) FROM public.orders),
    total_sales=(SELECT coalesce(sum(amount),0) FROM public.orders WHERE status IN ('paid','success','completed')),
    total_revenue=(SELECT coalesce(sum(fee),0) FROM public.transactions WHERE type='sale_earning'),
    updated_at=now()
WHERE id=1;



-- RPC SIGNATURES VERIFIED AGAINST USER-PROVIDED INVENTORY: admin_adjust_balance, admin_bots, admin_cancel_order, admin_content, admin_delete_bot, admin_delete_content, admin_delete_paste, admin_delete_product, admin_logs, admin_mark_order_paid, admin_orders, admin_pastes, admin_payment_methods, admin_payments, admin_process_withdrawal, admin_products, admin_publish_announcement, admin_save_socials, admin_set_bot_active, admin_set_user, admin_site_stats, admin_stats, admin_transactions, admin_update_content, admin_update_product, admin_upsert_bot, admin_users, admin_withdrawals

-- ============================================================
-- SECURITY VERIFICATION
-- ============================================================
DO $$
DECLARE
  rel_kind char;
  rel_options text[];
BEGIN
  SELECT c.relkind, c.reloptions
    INTO rel_kind, rel_options
  FROM pg_class c
  JOIN pg_namespace n ON n.oid = c.relnamespace
  WHERE n.nspname='public' AND c.relname='profile_public';

  IF rel_kind <> 'v' THEN
    RAISE EXCEPTION 'profile_public was not created as a view';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM unnest(coalesce(rel_options, ARRAY[]::text[])) AS x(opt)
    WHERE lower(opt) LIKE 'security_barrier=%'
  ) THEN
    RAISE NOTICE 'profile_public has security_barrier enabled';
  END IF;
END $$;



-- ============================================================

COMMIT;