(() => {'use strict';
const A=window.PasTeleAdmin,$=A.$;let items=[];
const date=v=>{try{return new Date(v).toLocaleString('id-ID',{dateStyle:'medium',timeStyle:'short'})}catch(_){return String(v||'')}};
function reset(){ $('#announcementId').value='';$('#announcementTitle').value='';$('#announcementBody').value='';$('#announcementImage').value='';$('#announcementPublished').checked=true;$('#editorTitle').textContent='Buat pengumuman';$('#editStatus').textContent='Baru';$('#saveAnnouncement').innerHTML='<i class="fa-solid fa-paper-plane"></i> Simpan Pengumuman';}
function edit(id){const r=items.find(x=>String(x.id)===String(id));if(!r)return;$('#announcementId').value=r.id||'';$('#announcementTitle').value=r.title||'';$('#announcementBody').value=r.body||'';$('#announcementImage').value=r.image_url||'';$('#announcementPublished').checked=r.published!==false;$('#editorTitle').textContent='Edit pengumuman';$('#editStatus').textContent=r.published?'Terbit':'Draft';$('#saveAnnouncement').innerHTML='<i class="fa-solid fa-floppy-disk"></i> Simpan Perubahan';window.scrollTo({top:0,behavior:'smooth'});}
function render(){const b=$('#announcementList');if(!items.length){b.innerHTML='<div class="empty"><i class="fa-solid fa-bullhorn"></i><strong>Belum ada pengumuman</strong><span>Buat pengumuman pertama dari form di sebelah kiri.</span></div>';return}b.innerHTML=items.map(r=>`<article class="announcement-item"><div class="announcement-item-head"><div><h3>${A.esc(r.title)}</h3><div class="announcement-meta"><span><i class="fa-regular fa-clock"></i> ${A.esc(date(r.published_at||r.created_at))}</span></div></div><span class="announcement-status ${r.published?'published':'draft'}">${r.published?'TERBIT':'DRAFT'}</span></div><p>${A.esc(r.body||'')}</p>${r.image_url?`<img class="announcement-image" src="${A.esc(r.image_url)}" alt="" loading="lazy">`:''}<div class="announcement-actions"><button class="btn" data-edit="${A.esc(r.id)}"><i class="fa-solid fa-pen"></i> Edit</button><button class="btn danger" data-delete="${A.esc(r.id)}"><i class="fa-solid fa-trash"></i> Hapus</button></div></article>`).join('');}
async function load(){try{if(!(await A.requireAdmin()))return;items=await A.rpc('admin_announcements',{p_limit:100,p_offset:0});render()}catch(e){console.error(e);A.toast(A.errText(e),'error');$('#announcementList').innerHTML=`<div class="empty error-state"><i class="fa-solid fa-triangle-exclamation"></i><strong>Gagal memuat</strong><span>${A.esc(A.errText(e))}</span></div>`}}
async function save(e){e.preventDefault();const title=$('#announcementTitle').value.trim(),body=$('#announcementBody').value.trim(),image=$('#announcementImage').value.trim()||null,published=$('#announcementPublished').checked;if(!title)return A.toast('Judul wajib diisi.','error');if(!body)return A.toast('Isi pengumuman wajib diisi.','error');const btn=$('#saveAnnouncement');btn.disabled=true;try{await A.call('admin_upsert_announcement',{p_id:$('#announcementId').value||null,p_title:title,p_body:body,p_image_url:image,p_published:published});A.toast(published?'Pengumuman diterbitkan.':'Pengumuman disimpan sebagai draft.');reset();await load()}catch(e){console.error(e);A.toast(A.errText(e),'error')}finally{btn.disabled=false}}
async function remove(id){const r=items.find(x=>String(x.id)===String(id));if(!r||!confirm(`Hapus pengumuman "${r.title}"?`))return;try{await A.call('admin_delete_announcement',{p_id:id});A.toast('Pengumuman dihapus.');await load()}catch(e){console.error(e);A.toast(A.errText(e),'error')}}
document.addEventListener('DOMContentLoaded',async()=>{$('#announcementForm').addEventListener('submit',save);$('#cancelEdit').addEventListener('click',reset);$('#newAnnouncement').addEventListener('click',()=>{reset();window.scrollTo({top:0,behavior:'smooth'})});$('#refreshAnnouncements').addEventListener('click',load);document.addEventListener('click',e=>{const a=e.target.closest('[data-edit]'),d=e.target.closest('[data-delete]');if(a)edit(a.dataset.edit);if(d)remove(d.dataset.delete)});await load()});
})();