(() => {'use strict'; const A=window.PasTeleAdmin,$=A.$; let controls={};
const labels={forum_chat:['forum','Forum Chat'],withdrawal_instant:['instant','WD Instan'],withdrawal_manual:['manual','WD Manual']};
function bool(v){return v===true||String(v).toLowerCase()==='true';}
async function loadControls(){const data=await A.call('get_public_site_settings');const s=data||{};controls={};Object.keys(labels).forEach(k=>controls[k]={enabled:s[k]?.enabled!==false,reason:s[k]?.reason||''});render();}
function render(){Object.entries(labels).forEach(([k,[id,label]])=>{const c=controls[k];const b=$('#'+id+'Badge'),t=$('#'+id+'Toggle'),p=$('#'+id+'StatusText'),w=$('#'+id+'ReasonWrap'),r=$('#'+id+'Reason');if(!c)return;b.textContent=c.enabled?'AKTIF':'DITUTUP';b.className='control-status '+(c.enabled?'on':'off');p.textContent=c.enabled?'Fitur tersedia untuk pengguna.':(c.reason||'Fitur ditutup admin.');t.innerHTML=`<i class="fa-solid fa-${c.enabled?'power-off':'play'}"></i> ${c.enabled?'Tutup':'Buka'} ${label}`;t.className='btn control-toggle '+(c.enabled?'danger':'success');r.value=c.reason||'';w.classList.toggle('hidden',c.enabled);});}
async function toggle(k){const c=controls[k];const id=labels[k][0];let reason='';if(c.enabled){reason=$('#'+id+'Reason').value.trim();if(!reason){A.toast('Isi alasan penutupan terlebih dahulu.','error');return;}}else if(!confirm(`Buka kembali ${labels[k][1]}?`))return;const b=$('#'+id+'Toggle');b.disabled=true;try{await A.call('admin_set_platform_control',{p_section:k,p_enabled:!c.enabled,p_reason:reason});await loadControls();A.toast(c.enabled?'Fitur ditutup.':'Fitur dibuka.')}catch(e){A.toast(A.errText(e),'error')}finally{b.disabled=false}}
async function stats(){const d=await A.rpc('admin_stats');const r=d[0]||{};const cards=[['fa-users','Users',r.total_users??0],['fa-box','Products',r.total_products??0],['fa-receipt','Paid Orders',r.paid_orders??0],['fa-money-bill-transfer','Pending WD',r.pending_withdrawals??0],['fa-eye','Views',r.views??0],['fa-coins','Gross Sales',A.money(r.gross_sales??0)]];$('#statsGrid').innerHTML=cards.map(x=>`<div class="admin-stat"><span class="stat-icon"><i class="fa-solid ${x[0]}"></i></span><div><small>${A.esc(x[1])}</small><strong>${A.esc(x[2])}</strong></div></div>`).join('');}
async function load(){try{const g=await A.requireAdmin();if(!g)return;await Promise.all([loadControls(),stats()]);}catch(e){console.error(e);A.toast(A.errText(e),'error');}}
document.addEventListener('click',e=>{const b=e.target.closest('[data-control]');if(b)toggle(b.dataset.control)});$('#refreshAll')?.addEventListener('click',load);document.addEventListener('DOMContentLoaded',load);
})();
