(() => {
'use strict';
const A=window.PasTeleAdmin,$=A.$;let data=[];
async function load(){const box=$('#adminContent');A.setLoading(box);try{if(!await A.requireAdmin())return;data=await A.rpc('admin_orders',{p_limit:500,p_offset:0});render()}catch(e){box.innerHTML=`<div class="empty error-state"><i class="fa-solid fa-triangle-exclamation"></i><strong>Gagal memuat order</strong><span>${A.esc(A.errText(e))}</span></div>`}}
function render(){const box=$('#adminContent');box.innerHTML=`<div class="admin-toolbar"><div class="toolbar-title"><i class="fa-solid fa-receipt"></i><div><strong>Orders</strong><span id="count">${data.length} data</span></div></div><div class="toolbar-tools"><input id="search" class="admin-input" placeholder="Cari ID Order / username / email..."><select id="status" class="admin-input"><option value="">Semua status</option><option value="pending">Pending</option><option value="paid">Paid / Success</option><option value="success">Success</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select><button class="btn" id="reload"><i class="fa-solid fa-rotate"></i> Refresh</button></div></div><div id="adminTable"></div>`;paint(data);$('#search').oninput=filter;$('#status').onchange=filter;$('#reload').onclick=load}
function filter(){const q=($('#search').value||'').toLowerCase(),s=$('#status').value;paint(data.filter(r=>(!s||String(r.status||'').toLowerCase()===s)&&(!q||`${r.id||''} ${r.order_id||''} ${r.username||''} ${r.auth_email||''}`.toLowerCase().includes(q))))}
function paint(rows){$('#count').textContent=`${rows.length} data`;A.table($('#adminTable'),rows,[
{label:'Order ID',render:r=>`<strong>${A.esc(r.id||r.order_id||'-')}</strong><small>${A.esc(r.product_id||r.item_id||'-')}</small>`},
{label:'Username',render:r=>`<strong>${A.esc(r.username||'-')}</strong><small>${A.esc(r.auth_email||r.buyer_id||'-')}</small>`},
{label:'Amount',render:r=>A.money(r.amount)},
{label:'Status',render:r=>`<span class="status ${['success','paid','completed'].includes(String(r.status).toLowerCase())?'success':['failed','rejected','cancelled'].includes(String(r.status).toLowerCase())?'danger':''}">${A.esc(r.status||'-')}</span>`},
{label:'Created',render:r=>r.created_at?new Date(r.created_at).toLocaleString('id-ID'):'-'}
],r=>`<button class="btn small success" data-id="${A.esc(r.id)}" data-action="success"><i class="fa-solid fa-check"></i> Success</button> <button class="btn small danger" data-id="${A.esc(r.id)}" data-action="failed"><i class="fa-solid fa-xmark"></i> Failed</button> <button class="btn small danger" data-id="${A.esc(r.id)}" data-action="delete"><i class="fa-solid fa-trash"></i></button>`)}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action][data-id]');if(!b)return;try{if(b.dataset.action==='delete'){if(!confirm('Hapus order ini?'))return;await A.call('admin_delete_order',{p_order_id:b.dataset.id})}else{await A.call('admin_update_order_status',{p_order_id:b.dataset.id,p_status:b.dataset.action==='success'?'success':'failed'})}A.toast('Order diperbarui.');await load()}catch(x){A.toast(A.errText(x),'error')}});
document.addEventListener('DOMContentLoaded',load);
})();