(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
function setTheme(){const m=localStorage.getItem("pastele-theme")||"system";const d=m==="dark"||(m==="system"&&matchMedia("(prefers-color-scheme:dark)").matches);document.documentElement.dataset.theme=d?"dark":"light";document.documentElement.dataset.themeMode=m;document.documentElement.style.colorScheme=d?"dark":"light"}
setTheme();
window.Admin=window.Admin||{};
Object.assign(Admin,{esc,money,
 toast(msg,type="info"){let t=$("#adminToast");if(!t){t=document.createElement("div");t.id="adminToast";t.className="toast";document.body.append(t)}t.textContent=msg;t.style.background=type==="error"?"#b42318":"#142033";clearTimeout(window.__adminToast);window.__adminToast=setTimeout(()=>t.remove(),3500)},
 async guard(){if(!window.sb?.auth)throw Error("Supabase Auth belum siap.");const a=await sb.auth.getUser();if(a.error||!a.data?.user){location.replace("../login.html");throw Error("Sesi login tidak ditemukan.")}const u=a.data.user;let p=null;try{const q=await sb.from("profiles").select("*").eq("id",u.id).maybeSingle();if(q.error)throw q.error;p=q.data}catch(e){throw Error("Gagal membaca profil admin: "+e.message)}if(p?.is_banned){await sb.auth.signOut();location.replace("../login.html");throw Error("Akun diblokir.")}const role=String(p?.role||"").toLowerCase();if(p?.is_admin!==true&&!["admin","owner","superadmin"].includes(role)){location.replace("../dashboard.html");throw Error("Akses admin ditolak.")}Admin.user=u;Admin.profile=p;return{user:u,profile:p}},
 async rpc(name,params={}){if(!window.sb)throw Error("Supabase belum siap.");const r=await sb.rpc(name,params);if(r.error)throw r.error;return r.data},
 table(data){const a=Array.isArray(data)?data:(data?[data]:[]);if(!a.length)return'<div class="admin-empty"><div><i class="fa-regular fa-folder-open"></i><div>Tidak ada data.</div></div></div>';const keys=[...new Set(a.flatMap(x=>Object.keys(x||{})))];return`<div class="table-wrap"><table class="admin-table"><thead><tr>${keys.map(k=>`<th>${esc(k.replaceAll("_"," "))}</th>`).join("")}</tr></thead><tbody>${a.map(x=>`<tr>${keys.map(k=>`<td>${esc(x?.[k]??"—")}</td>`).join("")}</tr>`).join("")}</tbody></table></div>`},
 nav(){const h=$("#navbar");if(!h)return;h.innerHTML=`<header class="admin-topbar"><div class="admin-top-inner"><a class="admin-brand" href="index.html"><span class="admin-brand-mark"><i class="fa-solid fa-bolt"></i></span><span><b>PasTele</b><small>Admin Console</small></span></a><div class="admin-actions"><span class="admin-live"><i class="fa-solid fa-circle"></i> SECURE</span><button class="btn" id="adminTheme" title="Theme"><i class="fa-solid fa-circle-half-stroke"></i></button><a class="btn hide-mobile" href="../dashboard.html"><i class="fa-solid fa-arrow-left"></i> Dashboard</a><button class="btn danger" id="adminLogout"><i class="fa-solid fa-right-from-bracket"></i><span class="hide-mobile"> Logout</span></button></div></div></header>`;$("#adminTheme").onclick=()=>{localStorage.setItem("pastele-theme",(localStorage.getItem("pastele-theme")==="dark")?"light":"dark");setTheme()};$("#adminLogout").onclick=async()=>{if(!confirm("Logout dari Admin Console?"))return;try{await sb.auth.signOut({scope:"global"})}finally{location.replace("../login.html")}}}
});
document.addEventListener("DOMContentLoaded",()=>Admin.nav());
})();