/* PasTele Admin Core — SQL-aligned runtime */
(()=>{'use strict';
const CONFIG={SUPABASE_URL:'https://jxrndamvelqwhbcromye.supabase.co',SUPABASE_ANON_KEY:'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4cm5kYW12ZWxxd2hiY3JvbXllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg4ODIzNTIsImV4cCI6MjEwNDQ1ODM1Mn0.M8bqTbSadCPLdWORE769BVBt7hr0VcYfrIWmjHpnfXo'};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(Number(v||0));
const rows=v=>Array.isArray(v)?v:(v==null||v===''?[]:[v]);
function theme(){const k='pastele-theme',m=localStorage.getItem(k)||'system';const dark=m==='dark'||(m==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);document.documentElement.dataset.theme=dark?'dark':'light';document.documentElement.dataset.themeMode=m;document.documentElement.style.colorScheme=dark?'dark':'light';}
try{theme();matchMedia('(prefers-color-scheme: dark)').addEventListener?.('change',()=>{if((localStorage.getItem('pastele-theme')||'system')==='system')theme()})}catch{}
if(!window.sb){if(!window.supabase)throw new Error('Supabase library belum dimuat.');window.sb=window.supabase.createClient(CONFIG.SUPABASE_URL,CONFIG.SUPABASE_ANON_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:'pastele-auth',flowType:'pkce'}})}
window.TC=window.TC||{};Object.assign(window.TC,{esc,money,toast(msg,type='info'){let t=document.getElementById('toast');if(!t){t=document.createElement('div');t.id='toast';document.body.appendChild(t)}t.className='toast';t.textContent=String(msg);Object.assign(t.style,{position:'fixed',right:'16px',bottom:'16px',zIndex:9999,padding:'12px 15px',borderRadius:'12px',background:type==='error'?'#b42318':'#142033',color:'#fff',boxShadow:'0 12px 30px rgba(0,0,0,.2)',maxWidth:'calc(100vw - 32px)'});clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.remove(),3200)}});
window.Admin={...(window.Admin||{}),rows,esc,money,async rpc(name,params={}){const q=await sb.rpc(name,params);if(q.error)throw q.error;return q.data},async guard(){const a=await sb.auth.getUser();if(a.error||!a.data?.user){location.replace('../login.html');throw new Error('Sesi login tidak ditemukan.')};const u=a.data.user;const q=await sb.from('profiles').select('id,is_admin,is_banned,role,username,display_name,auth_email').eq('id',u.id).maybeSingle();if(q.error)throw q.error;const p=q.data;if(p?.is_banned){await sb.auth.signOut();location.replace('../login.html');throw new Error('Akun diblokir.')};if(!(p?.is_admin===true||['admin','owner'].includes(String(p?.role||'').toLowerCase()))){location.replace('../dashboard.html');throw new Error('Akses admin ditolak.')};return{user:u,profile:p}},format(v){if(v===null||v===undefined||v==='')return '<span class="muted">—</span>';if(typeof v==='boolean')return v?'<span class="badge"><i class="fa-solid fa-check"></i> Ya</span>':'<span class="badge"><i class="fa-solid fa-xmark"></i> Tidak</span>';if(typeof v==='object')return '<code>'+esc(JSON.stringify(v))+'</code>';return esc(v)},table(data){const r=rows(data);if(!r.length)return '<div class="empty"><i class="fa-regular fa-folder-open"></i><br>Tidak ada data.</div>';const keys=[...new Set(r.flatMap(x=>Object.keys(x||{})))];return '<div class="table-wrap"><table class="table"><thead><tr>'+keys.map(k=>'<th>'+esc(k.replaceAll('_',' '))+'</th>').join('')+'</tr></thead><tbody>'+r.map(x=>'<tr>'+keys.map(k=>'<td>'+this.format(x?.[k])+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'},mountNav(){const host=document.getElementById('navbar');if(!host)return;const path=location.pathname.split('/').pop()||'index.html';host.innerHTML='<div class="admin-topbar"><a class="brand" href="index.html"><span class="brand-mark"><i class="fa-solid fa-bolt"></i></span><span>PasTele <small style="display:block;color:var(--muted);font-size:10px">Admin Console</small></span></a><div class="top-actions"><button class="theme-btn" id="themeToggle" title="Tema"><i class="fa-solid fa-circle-half-stroke"></i></button><a class="btn" href="../dashboard.html"><i class="fa-solid fa-arrow-left"></i><span>Dashboard</span></a></div></div>';document.getElementById('themeToggle').onclick=()=>{const cur=localStorage.getItem('pastele-theme')||'system';localStorage.setItem('pastele-theme',cur==='dark'?'light':'dark');theme()};document.querySelectorAll('.admin-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===path))}};
document.addEventListener('DOMContentLoaded',()=>Admin.mountNav());
})();
