(()=>{"use strict";
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const money=v=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(v||0));
const rows=v=>Array.isArray(v)?v:(v==null||v===""?[]:[v]);
function theme(){ if(window.PasTeleTheme?.apply) return window.PasTeleTheme.apply(); }
if(!window.sb){const c=window.PASTELE_CONFIG||{},u=c.SUPABASE_URL||"https://jxrndamvelqwhbcromye.supabase.co",k=c.SUPABASE_ANON_KEY||"";if(window.supabase&&u&&k)window.sb=window.supabase.createClient(u,k,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true,storageKey:"pastele-auth",flowType:"pkce"}})}
window.TC=window.TC||{};TC.esc=esc;TC.money=money;TC.toast=(msg,type="info")=>{let t=document.getElementById("toast");if(!t){t=document.createElement("div");document.body.appendChild(t)}t.textContent=msg;t.style.cssText=`position:fixed;right:16px;bottom:16px;z-index:9999;padding:13px 16px;border-radius:13px;background:${type==="error"?"#b42318":"#142033"};color:#fff;box-shadow:0 12px 30px #0003;max-width:calc(100vw - 32px)`;clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.remove(),3200)};
window.Admin={rows,esc,money,
async rpc(n,p={}){if(!sb)throw Error("Supabase belum siap.");const q=await sb.rpc(n,p);if(q.error)throw q.error;return q.data},
async guard(){if(!sb?.auth)throw Error("Supabase Auth belum siap.");const a=await sb.auth.getUser();if(a.error||!a.data?.user){location.replace("../login.html");throw Error("Sesi login tidak ditemukan.")}const u=a.data.user,q=await sb.from("profiles").select("id,is_admin,is_banned,role,username,display_name,auth_email,balance").eq("id",u.id).maybeSingle();if(q.error)throw q.error;const p=q.data;if(p?.is_banned){await sb.auth.signOut();location.replace("../login.html");throw Error("Akun diblokir.")}if(!(p?.is_admin===true||["admin","owner","superadmin"].includes(String(p?.role||"").toLowerCase()))){location.replace("../dashboard.html");throw Error("Akses admin ditolak.")}Admin.current={user:u,profile:p};return Admin.current},
format(v){if(v===null||v===undefined||v==="")return'<span class="muted">—</span>';if(typeof v==="boolean")return v?'<span class="badge">✓ Ya</span>':'<span class="badge">× Tidak</span>';if(typeof v==="object")return"<code>"+esc(JSON.stringify(v))+"</code>";return esc(v)},
table(data){const r=rows(data);if(!r.length)return'<div class="empty">Tidak ada data.</div>';const k=[...new Set(r.flatMap(x=>Object.keys(x||{})))];return'<div class="table-wrap"><table><thead><tr>'+k.map(x=>"<th>"+esc(x.replaceAll("_"," "))+"</th>").join("")+"</tr></thead><tbody>"+r.map(x=>"<tr>"+k.map(y=>"<td>"+this.format(x?.[y])+"</td>").join("")+"</tr>").join("")+"</tbody></table></div>"},
mountNav(){const h=document.getElementById("navbar");if(!h)return;h.innerHTML=`<header class="admin-topbar"><div class="admin-topbar-inner"><a class="admin-brand" href="index.html"><span class="admin-brand-mark"><i class="fa-solid fa-bolt"></i></span><span><b>PasTele</b><small>Admin Console</small></span></a><div class="admin-top-actions"><span class="admin-live"><i class="fa-solid fa-circle"></i> SECURE</span><button class="theme-btn btn" id="themeToggle"><i class="fa-solid fa-circle-half-stroke"></i></button><a class="btn" href="../dashboard.html"><i class="fa-solid fa-arrow-left"></i><span>Dashboard</span></a><button class="btn danger" id="adminLogout"><i class="fa-solid fa-right-from-bracket"></i><span>Logout</span></button></div></div></header>`;themeToggle.onclick=()=>{const x=localStorage.getItem("pastele-theme")||"system";window.PasTeleTheme?.cycle?.()};adminLogout.onclick=async()=>{if(confirm("Keluar dari Admin Console?")){try{await sb.auth.signOut({scope:"global"})}finally{location.replace("../login.html")}}}}
};document.addEventListener("DOMContentLoaded",()=>Admin.mountNav())})();