(async()=>{
  const $=id=>document.getElementById(id), list=$('contentList'), toast=(m,t)=>TC.toast(m,t);
  const norm=x=>String(x||'').toLowerCase();
  let all=[], filtered=[], page=1, perPage=20, editing=null;
  function status(x){return x.source==='pastelinks'?(x.status==='published'?'published':norm(x.status||'hidden')):norm(x.status||'draft')}
  function type(x){return x.type||({products:'product',pastelinks:'link',telegram_products:'code',telegram_channels:'channel'}[x.source]||'product')}
  function icon(t){return ({product:'fa-box',link:'fa-link',code:'fa-code',channel:'fa-broadcast-tower',group:'fa-users'}[t]||'fa-layer-group')}
  function creator(x){return x.creator_name||x.creator_username||x.username||'Unknown'}
  async function load(){list.innerHTML='<div class="card admin-loading"><i class="fa-solid fa-spinner fa-spin"></i> Memuat konten...</div>';all=Admin.rows(await Admin.rpc('admin_content',{p_limit:500,p_offset:0}));render()}
  function render(){const q=norm($('contentSearch').value.trim()),t=$('contentType').value,s=$('contentStatus').value,sort=$('contentSort').value;filtered=all.filter(x=>(!q||[x.title,x.name,x.slug,creator(x)].some(v=>norm(v).includes(q)))&&(t==='all'||type(x)===t)&&(s==='all'||status(x)===s));filtered.sort((a,b)=>sort==='oldest'?new Date(a.created_at)-new Date(b.created_at):sort==='views'?Number(b.views||0)-Number(a.views||0):sort==='sales'?Number(b.sales_count||0)-Number(a.sales_count||0):sort==='price'?Number(b.price||0)-Number(a.price||0):new Date(b.created_at)-new Date(a.created_at));
    $('contentResult').textContent=`${filtered.length.toLocaleString('id-ID')} konten ditemukan`;
    const start=(page-1)*perPage,vis=filtered.slice(start,start+perPage); $('contentKpis').innerHTML=[['Total',all.length,'fa-layer-group'],['Published',all.filter(x=>status(x)==='published').length,'fa-circle-check'],['Creator',new Set(all.map(x=>x.creator_id||x.owner_id||x.user_id).filter(Boolean)).size,'fa-users'],['Views',all.reduce((n,x)=>n+Number(x.views||0),0).toLocaleString('id-ID'),'fa-eye']].map(x=>`<div class="content-kpi"><div class="content-kpi-icon"><i class="fa-solid ${x[2]}"></i></div><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');
    list.innerHTML=vis.length?vis.map(x=>`<article class="content-item"><div class="content-type-icon"><i class="fa-solid ${icon(type(x))}"></i></div><div class="content-main"><div class="content-title"><strong>${Admin.esc(x.title||x.name||'Untitled')}</strong><span class="content-pill">${Admin.esc(type(x))}</span></div><div class="content-sub"><span>Slug: ${Admin.esc(x.slug||'—')}</span><span>·</span><span>Creator: ${Admin.esc(creator(x))}</span></div><div class="content-meta"><span class="content-pill ${Admin.esc(status(x))}">${Admin.esc(status(x))}</span><span class="content-pill"><i class="fa-solid fa-eye"></i> ${Number(x.views||0).toLocaleString('id-ID')}</span><span class="content-pill"><i class="fa-solid fa-cart-shopping"></i> ${Number(x.sales_count||0).toLocaleString('id-ID')}</span><span class="content-pill">${Number(x.price||0)>0?Admin.money(x.price):'Gratis'}</span></div></div><div class="content-actions"><button class="btn icon-only" data-edit="${Admin.esc(x.id)}" title="Edit"><i class="fa-solid fa-pen"></i></button><button class="btn danger icon-only" data-delete="${Admin.esc(x.id)}" title="Hapus"><i class="fa-solid fa-trash"></i></button></div></article>`).join(''):'<div class="card content-empty empty"><i class="fa-regular fa-folder-open"></i><br>Tidak ada konten yang cocok.</div>';
    vis.forEach(x=>{list.querySelector(`[data-edit="${CSS.escape(String(x.id))}"]`)?.addEventListener('click',()=>open(x));list.querySelector(`[data-delete="${CSS.escape(String(x.id))}"]`)?.addEventListener('click',()=>del(x))});
    const pages=Math.max(1,Math.ceil(filtered.length/perPage));const pg=$('contentPagination');pg.hidden=pages<=1;pg.innerHTML=pages>1?Array.from({length:pages},(_,i)=>`<button data-p="${i+1}" class="${i+1===page?'active':''}">${i+1}</button>`).join(''):'';pg.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>{page=Number(b.dataset.p);render()});
  }
  function open(x){editing=x;$('editId').value=x.id;$('editSource').value=x.source;$('editTitle').value=x.title||x.name||'';$('editSlug').value=x.slug||'';$('editPrice').value=Number(x.price||0);$('editStatus').value=status(x)==='public'?'published':status(x);$('editDescription').value=x.description||'';$('editSlug').disabled=x.source!=='products';$('editNote').textContent=x.source==='pastelinks'?'PasteLink memakai visibility public/hidden di SQL.':'Editor menggunakan RPC admin_update_content pada SQL master.';$('contentModal').hidden=false;$('contentModal').setAttribute('aria-hidden','false')}
  function close(){$('contentModal').hidden=true;$('contentModal').setAttribute('aria-hidden','true');editing=null}
  async function save(e){e.preventDefault();if(!editing)return;const payload={p_id:editing.id,p_source:editing.source,p_title:$('editTitle').value.trim()||null,p_slug:$('editSlug').value.trim()||null,p_price:Number($('editPrice').value||0),p_status:$('editStatus').value,p_description:$('editDescription').value.trim()||null};try{await Admin.rpc('admin_update_content',payload);toast('Konten diperbarui','success');close();await load()}catch(e){toast(e.message,'error')}}
  async function del(x){if(!confirm(`Hapus konten "${x.title||x.name||'Untitled'}"?`))return;try{await Admin.rpc('admin_delete_content',{p_id:x.id,p_source:x.source});toast('Konten dihapus','success');await load()}catch(e){toast(e.message,'error')}}
  try{await Admin.guard();$('contentSearch').oninput=()=>{page=1;render()};$('contentType').onchange=()=>{page=1;render()};$('contentStatus').onchange=()=>{page=1;render()};$('contentSort').onchange=()=>{page=1;render()};$('clearContentSearch').onclick=()=>{$('contentSearch').value='';page=1;render()};$('resetContentFilters').onclick=()=>{$('contentSearch').value='';$('contentType').value='all';$('contentStatus').value='all';$('contentSort').value='newest';page=1;render()};$('refreshContent').onclick=load;$('contentEditForm').onsubmit=save;$('contentModalClose').onclick=close;$('cancelContentEdit').onclick=close;$('[data-close-content]')?.addEventListener('click',close);$('deleteContent').onclick=()=>editing&&del(editing);await load()}catch(e){list.innerHTML=`<div class="card empty">${Admin.esc(e.message)}</div>`}
})();
