window.TELECOD_CONFIG={
  SUPABASE_URL:"https://YOUR_PROJECT.supabase.co",
  SUPABASE_ANON_KEY:"YOUR_PUBLISHABLE_OR_ANON_KEY",
  TELEGRAM_BOT_USERNAME:"YOUR_BOT_USERNAME",
  TELEGRAM_AUTH_FUNCTION_URL:"https://YOUR_PROJECT.supabase.co/functions/v1/telegram-login",
  USERNAME_AUTH_FUNCTION_URL:"https://YOUR_PROJECT.supabase.co/functions/v1/username-auth",
  MARKETPLACE_FUNCTION_URL:"https://YOUR_PROJECT.supabase.co/functions/v1/marketplace",
  PAYMENT_CREATE_FUNCTION_URL:"https://YOUR_PROJECT.supabase.co/functions/v1/payment-create",
  PAYMENT_STATUS_FUNCTION_URL:"https://YOUR_PROJECT.supabase.co/functions/v1/payment-status",
  PAYMENT_WEBHOOK_URL:"https://YOUR_PROJECT.supabase.co/functions/v1/payment-webhook",
  SITE_URL:"https://YOUR-DOMAIN.example",
  DOMPETX_API_BASE:"https://api.dompetx.com",
  DOMPETX_PAYMENT_METHOD:"QRIS"
};
